# 4 NumPy and Pandas

## Introduction

After getting used to how Python works, it is the moment to begin getting our hands dirty with data analysis. We will study two packages: [NumPy](http://www.numpy.org/) is the fundamental numeric computing and linear algebra package in Python, that allows for decent data analysis. We will learn it not only for the data analysis, but more importantly because it will be a package that will be always present in our `import` section as scientists. After NumPy we will go to [Pandas](http://pandas.pydata.org/). Pandas is a dedicated data analysis package with a lot more functionalities than NumPy, making our life much easier in terms of data visualization and manipulation. All the power of Pandas will be completely unleashed in Section 5, where we will see how to visualize information in plots.

As usual, we begin importing the necessary packages

In [1]:
import numpy as np
import pandas as pd
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 1.13.1
Pandas: 0.20.3


## Numeric Python (NumPy)

NumPy is an open-source add-on module to Python that provides common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that
associated with common commercial software like MATLAB. The [NumPy](http://www.numpy.org/) (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. The main object NumPy works with is a *homogeneous multidimensional array*. Despite its intimidating name, these are nothing but tables of numbers, each labelled by a tuple of indices.

We will now explore some capabilities of NumPy that will prove very useful not only for data analyisis, but throughout all our life with Python.

### Creating Arrays

As mentioned before, the main object in NumPy is the *array*. Creating one is as easy as calling the command `array`

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
type(x)

numpy.ndarray

The same applies to multidimensional arrays

In [4]:
m = np.array([[[7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6]]])
m

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

There is one restriction with respect to the use of lists: while you could create lists with data of different type, all the data in an array has to be of the same type, and it will be converted automatically.

In [5]:
lst = [1., 'cat']
print(type(lst[0]))

arr = np.array(lst)
print(type(arr[0]))

<class 'float'>
<class 'numpy.str_'>


(We will go deeper into indexing in a while)

-----
A NumPy array has a number of dimensions (or *axes*). To obtain the number of axes and the size of each of them you use the command `shape`. For 2-dimensional arrays (matrices), the order corresponds to (rows, columns)

There are two different ways of calling the `shape` command, either with `np.shape(arr)` or `arr.shape`. This is not the only command that works in both formats, and we will be finding some more in our way.

In [6]:
print(x.shape)
print(np.shape(m))

(3,)
(2, 2, 3)


### Special Arrays

Now we review some built-in functions that create matrices commonly used. `ones` and `zeros` return arrays of given shape and type (default is float64), filled with ones or zeros, respectively.

In [7]:
array_zeros=np.zeros((3, 2))
array_ones=np.ones((3, 2, 4), dtype=np.int8)

In [8]:
array_zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [9]:
array_ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

`eye(d)` returns a 2-D, dimension-$d$ array with ones on the diagonal and zeros elsewhere.

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

`eye` can also create arrays with ones in upper and lower diagonals. To achieve this, you must call `eye(d, d, k)` where $k$ denotes the diagonal (positive for above the center diagonal, negative for below), or `eye(d, k=num)`

In [11]:
print(np.eye(5, 5, 2))
np.eye(5, k=-1)

[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

`diag`, depending on the input, either extracts a diagonal from a matrix (if the input is a 2-D array), or constructs a diagonal array (if the input is a vector).

In [12]:
np.diag(x, 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [13]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np.diag(y))
np.diag(np.diag(y))

[ 1  6 11 16]


array([[ 1,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 16]])

`arange(begin, end, step)` returns evenly spaced values within a given interval. Note that the beginning point is included, but not the ending.

In [14]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
len(n)

15

**Exercise 1 **: Create an array of the first million of odd numbers, both with `arange` and using loops. Try timing both methods to see which one is faster. For that, use `%timeit`.

In [16]:
%timeit np.arange(0, 2e6, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

1.09 ms ± 28.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
225 ms ± 11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Similarly, `linspace(begin, end, points)` returns evenly spaced numbers over a specified interval. Here, instead of specifying the step, you specify the amount of points you want. Also with `linspace` you include the ending of the interval.

In [17]:
o = np.linspace(0, 30, 15)
o

array([  0.        ,   2.14285714,   4.28571429,   6.42857143,
         8.57142857,  10.71428571,  12.85714286,  15.        ,
        17.14285714,  19.28571429,  21.42857143,  23.57142857,
        25.71428571,  27.85714286,  30.        ])

In [18]:
len(o)

15

`reshape` changes the shape of an array, but not its data. This is another of the commands that can be called before or after the array.

In [19]:
print(n.reshape(3, 5))
np.reshape(n, (5, 3))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

Note however that, in order for these changes to be permanent, you should do a reassignment of the variable

In [20]:
print(n)  # After the reshapings above, the original array stays being the same

n = n.reshape(3, 5)
n   # Now that we have reassigned it is when it definitely changes shape

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### Combining Arrays

The most general command for combining arrays is `concatenate(arrs, d)`. It takes a list of arrays and concatenates them along axis $d$

In [21]:
p = np.ones([2, 2, 2])
p

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [22]:
np.concatenate([p, 2 * p], 0)

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 2.,  2.],
        [ 2.,  2.]],

       [[ 2.,  2.],
        [ 2.,  2.]]])

In [23]:
np.concatenate([p, 2 * p], 1)

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 2.,  2.],
        [ 2.,  2.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 2.,  2.],
        [ 2.,  2.]]])

In [24]:
np.concatenate([p, 2 * p], 2)

array([[[ 1.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.]],

       [[ 1.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.]]])

However, for common combinations there exist special commands. Use `vstack` to stack arrays in sequence vertically (row wise), `hstack` to stack arrays in sequence horizontally (column wise), and `block` to create arrays out of blocks (only available in versions 1.13.0+)

In [25]:
q = np.ones((2, 2))
np.vstack([q, 2 * q])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 2.,  2.],
       [ 2.,  2.]])

In [26]:
np.hstack([q, 2 * q])

array([[ 1.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.]])

In [27]:
np.block([[q, np.zeros((2, 2))], [np.zeros((2, 2)), 2 * q]])

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  2.],
       [ 0.,  0.,  2.,  2.]])

### Operations

You can perform easily element-wise operations on arrays of any shape. Use the typical symbols, +, -, \*, / and \*\* to perform element-wise addition, subtraction, multiplication, division and power.

In [28]:
x = np.array([1, 2, 3])
print(x)
print(x + 10)
print(3 * x)
print(1 / x)
print(x ** (-2 / 3))
print(2 ** x)

[1 2 3]
[11 12 13]
[3 6 9]
[ 1.          0.5         0.33333333]
[ 1.          0.62996052  0.48074986]
[2 4 8]


Also (and obviously) these symbols can be used to operate between two arrays, which must be of the same shape. If this is the case, they also do element-wise operations

In [29]:
y = np.arange(4, 7, 1)
print(x + y)     # [1+4, 2+5, 3+6]
print(x * y)     # [1*4, 2*5, 3*6]
print(x / y)     # [1/4, 2/5, 3/6]
print(x ** y)    # [1**4, 2**5, 3**6]

[5 7 9]
[ 4 10 18]
[ 0.25  0.4   0.5 ]
[  1  32 729]


For doing vector or matrix multiplication, the command to be used is `dot`

In [30]:
x.dot(y) # 1*4 + 2*5 + 3*6

32

With python 3.5 matrix multiplication got it's own operator

In [31]:
x@y

32

In [32]:
X = np.array([[i + j for i in range(3, 6)] for j in range(3)])
Y = np.diag([1, 1], 1) + np.diag([1], -2)

print('{}\n'.format(X))
print(X * Y)
np.dot(X, Y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]

[[0 4 0]
 [0 0 6]
 [5 0 0]]


array([[5, 3, 4],
       [6, 4, 5],
       [7, 5, 6]])

**Exercise 2**: Take a 10x2 matrix representing $(x1,x2)$ coordinates and transform them into polar coordinates $(r,\theta)$.

*Hint 1: the inverse transformation is given by $x1 = r\cos\theta$, $x2 = r\sin\theta$*

*Hint 2: generate random numbers with the functions in numpy.random*

In [33]:
z = np.random.random((10, 2))
x1, x2 = z[:, 0], z[:, 1]
R = np.sqrt(x1 ** 2 + x2 ** 2)
T = np.arctan2(x2, x1)
print(R)
print(T)

[ 1.01238542  0.92547189  0.67252168  0.43065403  0.92116711  0.81600157
  1.0470755   0.38573654  0.84806441  0.90163748]
[ 1.05586934  0.3753704   1.37931721  0.33137075  0.19440469  0.35880173
  1.25204823  0.94770635  1.01710347  0.11118113]


#### Transposing

Transposition is a very important operation for linear algebra. Although NumPy is capable of correctly doing matrix-vector products correctly regardless of the orientation of the vector, it is not the case for products of matrices

In [34]:
Z = np.arange(0, 12, 1).reshape((4, 3))

In [35]:
np.dot(Z, y)

array([ 17,  62, 107, 152])

In [36]:
np.dot(Z, y.T)

array([ 17,  62, 107, 152])

In [37]:
Z.dot(X)

array([[ 14,  17,  20],
       [ 50,  62,  74],
       [ 86, 107, 128],
       [122, 152, 182]])

In [38]:
(Z.T).dot(X)

ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

#### Array Methods

To not have to go from NumPy arrays to lists back and forth, NumPy contains some functions to know properties of your arrays. Actually, there are more of these functions than in standard Python.

In [39]:
a = np.array([-4, -2, 1, 3, 5])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

5
-4
3
0.6
3.26190128606


Some interesting functions are `argmax` and `argmin`, which return the index of the maximum and minimum values in the array.

In [40]:
print(a.argmax())
print(a.argmin())

4
0


### Indexing/Slicing

We have already seen briefly that to access individual elements you use the bracket notation: `array[ax_0, ax_1, ...]`, where the `ax_i` denotes the coordinate in the `i`-th axis. You can even use this to assign new values to your elements.

In [41]:
r = [4, 5, 6, 7]
print(r[2])
r[0] = 198
r

6


[198, 5, 6, 7]

To select a range of rows or columns you can use a colon :. A second : can be used to indicate the step size. `array[start:stop:stepsize]`. If you leave `start` (`stop`) blank, the selection will go from the very beginning (until the very end) of the array

In [42]:
s = np.arange(13)**2
print(s)
print(s[3:9])
print(s[2:10:3])
s[-5::-2]

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[ 9 16 25 36 49 64]
[ 4 25 64]


array([64, 36, 16,  4,  0])

The same applies to matrices or higher-dimensional arrays

In [43]:
r = np.arange(36).reshape((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [44]:
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

You can also select specific rows and columns, separated by commas

In [45]:
r[[1, 3, 4], 1:3]

array([[ 7,  8],
       [19, 20],
       [25, 26]])

A very useful tool is *conditional indexing*, where we apply a function, assignment... only to those elements of an array that satisfy some condition

In [46]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Exercise 3**: Create a random 1-dimensional array, and find which element is closest to 0.7

In [47]:
Z = np.random.uniform(0,1,100)
z = 0.7
m = Z[np.abs(Z - z).argmin()]
print(m)

0.703501053849


#### Copying Data

**Be very careful with copying and modifying arrays in NumPy!** You will see the reason right now. Let's begin defining `r2` as a slice of r

In [48]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

And now let's set all its elements to zero

In [49]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

When looking at `r`, we see that it has also been changed!

In [50]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

The proper way of handling selections without modifying the original arrays is through the `copy` command.

In [51]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now we can safely modify `r_copy` without affecting `r`.

In [52]:
r_copy[:] = 10
print('{}\n'.format(r_copy))
r

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]



array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Iterating Over Arrays

Finally, you can iterate over arrays in the same way as you iterate over lists

In [53]:
test = np.random.randint(0, 10, (4,3))
test

array([[7, 7, 2],
       [0, 1, 3],
       [7, 6, 1],
       [9, 6, 8]])

You can iterate by row:

In [54]:
for row in test:
    print(row)

[7 7 2]
[0 1 3]
[7 6 1]
[9 6 8]


Or by row index

In [55]:
for i in range(len(test)):
    print(test[i])

[7 7 2]
[0 1 3]
[7 6 1]
[9 6 8]


Or by row and index:

In [56]:
for i, row in enumerate(test):
    print('Row {} is {}'.format(i, row))

Row 0 is [7 7 2]
Row 1 is [0 1 3]
Row 2 is [7 6 1]
Row 3 is [9 6 8]


In the same way as with lists, you can use `zip` to iterate over multiple iterables.

In [57]:
test2 = test**2
test2

array([[49, 49,  4],
       [ 0,  1,  9],
       [49, 36,  1],
       [81, 36, 64]])

In [58]:
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[7 7 2] + [49 49  4] = [56 56  6]
[0 1 3] + [0 1 9] = [ 0  2 12]
[7 6 1] + [49 36  1] = [56 42  2]
[9 6 8] + [81 36 64] = [90 42 72]


**Exercise 4**: Create a function that iterates over the columns of a 2-dimensional array

In [59]:
def iterate(df):
    for i, row in enumerate(df):
        shp = row.shape
        row.shape = shp + (1,)
        print('Column {} is {}'.format(i, row))

iterate(test.T)

Column 0 is [[7]
 [0]
 [7]
 [9]]
Column 1 is [[7]
 [1]
 [6]
 [6]]
Column 2 is [[2]
 [3]
 [1]
 [8]]


### Loading and Saving Data

To load and save data NumPy has the `loadtxt` and `savetxt` commands. However, they only work for two-dimensional arrays

In [60]:
np.savetxt('numpytest.txt', test)
np.loadtxt('numpytest.txt')

array([[ 7.,  7.,  2.],
       [ 0.,  1.,  3.],
       [ 7.,  6.,  1.],
       [ 9.,  6.,  8.]])

## Pandas

When dealing with numeric matrices and vectors in Python, NumPy makes life a lot easier. For more complex data, however, it leaves a bit to be desired. For those used to working with dedicated languages like R, doing data analysis directly with numpy feels like a step back. Fortunately, some nice folks have written the Python Data Analysis Library (a.k.a. [pandas](http://pandas.pydata.org/)). Pandas provides an R-like DataFrame, produces high quality plots with matplotlib, and integrates nicely with other libraries that expect NumPy arrays.

Pandas works with `Series` of data, that then are arranged in `DataFrame`s. A dataframe will be the object closest to an Excel spreadsheet that you will see throughout the course (but of course, given that it is integrated in Python and can be combined with so many different packages, dataframes are much more powerful than Excel spreadsheets). The data in the series can be either qualitative or quantitative data. Creating a series is as easy as creating a NumPy array from a one-dimensional list.

In [61]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [62]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

Notice that the series is indexed by default by integers. You can change this indexing by using a dictionary instead of a list for creating the series.

In [63]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

On the other hand, `DataFrame`s can be built from two-dimensional arrays, with the ability of labelling columns and indexing the rows

In [64]:
u = pd.DataFrame(np.random.randn(1000,6), index=np.arange(0, 3000, 3), 
                 columns=['A', 'B', 'C', 'D', 'E', 'F'])
u

A         B         C         D         E         F
0    -2.027348 -0.760066  1.818686 -0.616385  0.552074 -1.224706
3    -0.240134 -1.034095  0.678209 -0.204445 -0.439685  1.754732
6     0.152990 -0.655726 -1.630595  0.101850 -0.064469 -0.753385
9    -0.357923 -1.487928 -1.013571  2.227863  0.939255 -0.461609
12    0.304958 -1.514211 -0.053739  0.276051 -0.733645  0.942726
15   -0.239578  0.608844  1.739310 -0.543123  0.675398  1.665416
18   -0.883210  0.904198  0.378123 -1.176221 -1.243975  1.467087
21   -0.422791 -0.259483 -1.682882 -0.518549 -0.009037 -0.972062
24    1.254290 -1.980355 -0.208856 -0.106617  0.855234  0.195338
27   -0.411384  1.370993 -0.605932 -0.376451  0.590043  0.180325
30   -1.057850 -0.631944  0.555904  1.097064 -1.387151  0.353236
33   -0.711113 -0.169546  0.171976 -0.212092 -1.132355  1.315146
36    0.829969  0.297953 -0.302928 -0.945781 -0.242724  1.312581
39   -0.697625  1.229031  1.987020  0.343909  2.364586  0.450260
42    1.269170 -1.206863  0.878972  0.837160 -0.437905  0.348167
45   -0.407344 -0.071046  1.459191  1.619865 -0.440274  0.539111
48    0.374244 -0.697430  0.450782 -0.308440  0.228700  0.421094
51   -0.100464  1.401493  0.856901 -1.714850 -0.726944 -0.307432
54    1.227898  0.029258  0.303557  0.058012  0.911842 -0.323239
57    0.260521  0.902231  0.767018 -1.457077 -1.540407  0.214406
60    0.021719 -0.581770 -0.412024  0.199358  1.186086  1.977274
63    0.192915  1.176450 -0.215527  1.906917  0.590545 -1.208706
66    0.617869 -0.012514 -0.028533  0.506198 -0.256584 -0.535241
69    0.675479  1.217800 -0.078125 -1.803885  0.117571  0.667392
72   -0.406723 -0.155374 -1.444615 -0.637595 -1.395026  0.266084
75    0.198348  0.602034 -1.474521  0.306232  3.149443  2.307441
78   -0.793300  0.067512  0.437059 -0.252246  0.623072  0.594353
81   -1.085852  2.311401 -1.244005  0.247349  0.157492 -1.245686
84    0.247839 -0.077916 -0.762923 -0.555147 -0.114645  0.627074
87   -0.681611  0.226183 -0.976978  1.660791 -0.766767  1.677164
...        ...       ...       ...       ...       ...       ...
2910 -0.541525  1.038404  0.418874  1.730242  1.382714  0.991357
2913 -0.072480 -0.725895  1.516190 -1.728947 -0.041549  0.139706
2916  0.163878 -0.636558  0.553073 -1.364876  0.496830  0.312249
2919  0.686492  0.094363  0.835299  1.702522  1.135436  1.675020
2922 -0.027295  0.163613 -0.616894 -1.705558  0.762044  0.042091
2925 -2.315108  1.015217  1.062335  1.936149  1.821366  0.648717
2928 -0.411829 -0.732997  1.219275 -0.046593 -0.046027  3.003399
2931 -0.992891  0.501892 -0.630952  0.223819 -0.646514 -1.224562
2934 -0.550826  0.522783 -0.271546  1.439498 -0.013425  0.582987
2937  0.410123 -0.127677 -0.229596 -0.830667  0.071714  0.747561
2940  0.087771  0.252386 -0.959825  0.340264 -2.200490 -0.074453
2943 -3.003522 -1.629006  0.641945 -0.404185  0.716316  0.786389
2946  0.745290 -0.641602  1.073723 -0.448407 -0.046598  0.168012
2949 -2.961654  0.697773 -0.411028 -0.823714  1.253074  0.921263
2952  0.461372  0.963166 -0.387544 -1.167225  0.449699  0.416678
2955  0.643405  0.192321  1.981152  0.603926 -1.279414  1.097114
2958  0.122122  0.813402 -0.739232  0.547289 -1.337955 -1.105406
2961 -0.813555 -0.941517 -0.532860  0.754205 -1.290289 -0.612412
2964 -0.024280  0.542704 -0.594932  0.099559 -0.992261  0.596028
2967 -2.427947  0.160422  0.527004  1.206161  0.998892  0.529822
2970 -0.016148  1.763208 -1.034053  0.872201 -0.758887 -0.753172
2973  1.674303 -0.387506 -2.254331 -1.773518  0.615029 -1.716148
2976  2.119215  0.767200  0.782669 -0.044936  0.923013  0.825720
2979 -0.595234  0.600849  0.316792  0.253311  0.153847 -0.369398
2982 -0.708021 -1.713307 -0.552180 -0.307223 -0.939053 -0.820910
2985 -1.573937  0.308366 -1.662245  0.570210 -0.653210 -0.314402
2988 -1.194555  1.977206  0.754842  0.305322  1.198796  1.473283
2991  1.869433 -0.589284  0.759278 -0.351937 -0.536819  0.777580
2994  0.368289 -0.466715 -0.429377  0.289506 -0.339652 -0.339438
2997 -1.470242  1.698912  0.687847 -0.045696  0.

As you might have noticed, it is a bit ugly to deal with large dataframes. There are however some functions that allows to have an idea of the data in a frame.

In [65]:
u.head()

A         B         C         D         E         F
0  -2.027348 -0.760066  1.818686 -0.616385  0.552074 -1.224706
3  -0.240134 -1.034095  0.678209 -0.204445 -0.439685  1.754732
6   0.152990 -0.655726 -1.630595  0.101850 -0.064469 -0.753385
9  -0.357923 -1.487928 -1.013571  2.227863  0.939255 -0.461609
12  0.304958 -1.514211 -0.053739  0.276051 -0.733645  0.942726

In [66]:
u.tail()

A         B         C         D         E         F
2985 -1.573937  0.308366 -1.662245  0.570210 -0.653210 -0.314402
2988 -1.194555  1.977206  0.754842  0.305322  1.198796  1.473283
2991  1.869433 -0.589284  0.759278 -0.351937 -0.536819  0.777580
2994  0.368289 -0.466715 -0.429377  0.289506 -0.339652 -0.339438
2997 -1.470242  1.698912  0.687847 -0.045696  0.683194  1.892945

In [67]:
u.describe()

A            B            C            D            E  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     -0.015098     0.008872    -0.016395     0.037659     0.037678   
std       0.984677     1.027124     1.006594     1.005640     0.996846   
min      -3.003522    -3.206353    -3.043352    -3.009298    -3.261136   
25%      -0.684861    -0.632450    -0.669521    -0.669034    -0.632347   
50%      -0.017722     0.014125    -0.003506     0.021587     0.034067   
75%       0.647753     0.677340     0.672168     0.737131     0.684883   
max       3.102455     3.762320     3.692530     2.788648     4.026294   

                 F  
count  1000.000000  
mean      0.044510  
std       0.995552  
min      -3.081977  
25%      -0.665800  
50%       0.010477  
75%       0.695083  
max       3.120739

### Indexing/Slicing in Pandas

The easiest way of accessing information in a Pandas dataframe, equivalent to the way used in NumPy, is using the `iloc` command. With this you can also set specific values, do conditional indexing... all that we have seen before in section 2.4

In [68]:
u.iloc[125:132,[0, 2, 5]]

A         C         F
375  0.201490 -0.013349  0.894859
378  0.611214  0.054397  1.552808
381 -0.201816 -1.238886 -0.260646
384  0.234758 -0.459057  0.237965
387 -0.045797 -0.648149 -1.852657
390  1.387895 -1.123883  0.032155
393  1.381102  0.245459  0.437701

However, there are a few different ways of accessing the data in a Pandas dataframe, that typically have a more "direct" connection with the actual content fo the dataframe. Individual or sets of columns can also be accessed by their column names. Choosing one single column will give a Series, while two or more will produce a Dataset

In [69]:
u['A'].head()

0    -2.027348
3    -0.240134
6     0.152990
9    -0.357923
12    0.304958
Name: A, dtype: float64

In [70]:
u[['A', 'D']].head()

A         D
0  -2.027348 -0.616385
3  -0.240134 -0.204445
6   0.152990  0.101850
9  -0.357923  2.227863
12  0.304958  0.276051

Not only that, you can access a single column without the need of brackets []

In [71]:
u.A.head()

0    -2.027348
3    -0.240134
6     0.152990
9    -0.357923
12    0.304958
Name: A, dtype: float64

The usual [] will select specific rows according to the row number

In [72]:
u[0:10][list('BCF')]

B         C         F
0  -0.760066  1.818686 -1.224706
3  -1.034095  0.678209  1.754732
6  -0.655726 -1.630595 -0.753385
9  -1.487928 -1.013571 -0.461609
12 -1.514211 -0.053739  0.942726
15  0.608844  1.739310  1.665416
18  0.904198  0.378123  1.467087
21 -0.259483 -1.682882 -0.972062
24 -1.980355 -0.208856  0.195338
27  1.370993 -0.605932  0.180325

You can also choose specific rows according to their indices with the `loc` command

In [73]:
u.loc[6:15]

A         B         C         D         E         F
6   0.152990 -0.655726 -1.630595  0.101850 -0.064469 -0.753385
9  -0.357923 -1.487928 -1.013571  2.227863  0.939255 -0.461609
12  0.304958 -1.514211 -0.053739  0.276051 -0.733645  0.942726
15 -0.239578  0.608844  1.739310 -0.543123  0.675398  1.665416

Or, you can access just the elements that satisfy some condition

In [74]:
u[u.D > 2]

A         B         C         D         E         F
9    -0.357923 -1.487928 -1.013571  2.227863  0.939255 -0.461609
279  -1.693827  0.678455  0.251834  2.019776 -1.457883 -0.378174
309   0.185012  1.612854  1.842629  2.221449 -1.200267 -0.338037
630  -0.175075  0.683090  0.231274  2.788648  1.643279 -1.421536
633   0.985910 -1.817685 -1.244910  2.331280  0.245652 -0.570783
816   0.157696  0.677015 -0.339310  2.678451 -1.286623 -0.323133
822  -0.686627 -1.318971  0.607398  2.096694  0.537781 -0.765181
903  -0.404014  0.318842  0.454519  2.339301 -0.142463  0.577325
927   0.287234  0.516245 -0.599014  2.383027 -1.322511  1.252123
960   1.336699  0.097779  0.645317  2.114679  1.757087 -2.788128
1026  1.182023 -1.446403 -1.131362  2.254902 -0.771892  1.751744
1029  1.104195  0.602310 -1.168000  2.048645  0.290548  2.232469
1446  1.020657  1.612534 -0.058113  2.132320 -1.411498  0.048077
1533 -0.025136  0.707659  0.973447  2.225149  0.399693  0.959352
1587 -0.526426 -0.814235 -0.625573  2.667335 -0.724050 -0.834328
1626 -0.159947  1.272708  0.948115  2.094850  0.204254  1.049992
1680  0.391908  0.079890 -0.482793  2.634528 -0.104643  0.216905
1704  0.967906  2.143141  1.532862  2.038358  0.273596 -0.525668
1833  0.564158  0.078882  0.859239  2.560362 -0.022691  1.057235
2037  2.796273  1.516203 -0.497648  2.080990  1.451618 -1.027465
2142 -0.649937  1.082551 -1.224972  2.753773 -1.782158 -0.746023
2145  0.342255  0.450953  0.699056  2.195256  0.825626 -0.044388
2244 -0.675831  0.507642  0.456629  2.702892 -0.122744  1.610458
2352  0.043378 -1.032648 -1.502572  2.317046 -0.588368  0.436327
2379  0.456208 -0.033626  0.301799  2.348761 -0.102677 -1.196005
2547 -0.656553 -0.165790  0.237938  2.627635 -0.387519 -1.425041
2595 -0.869080 -0.109001  0.058407  2.380108 -0.208447 -0.457142
2688 -0.142271 -0.031213  2.070437  2.381172 -0.647984 -0.236080
2871 -0.336001  0.398215 -1.434569  2.109727 -0.660467  1.161468

In [76]:
u[~(u.D > 2)]  # For the inverse of u.D > 2

A         B         C         D         E         F
0    -2.027348 -0.760066  1.818686 -0.616385  0.552074 -1.224706
3    -0.240134 -1.034095  0.678209 -0.204445 -0.439685  1.754732
6     0.152990 -0.655726 -1.630595  0.101850 -0.064469 -0.753385
12    0.304958 -1.514211 -0.053739  0.276051 -0.733645  0.942726
15   -0.239578  0.608844  1.739310 -0.543123  0.675398  1.665416
18   -0.883210  0.904198  0.378123 -1.176221 -1.243975  1.467087
21   -0.422791 -0.259483 -1.682882 -0.518549 -0.009037 -0.972062
24    1.254290 -1.980355 -0.208856 -0.106617  0.855234  0.195338
27   -0.411384  1.370993 -0.605932 -0.376451  0.590043  0.180325
30   -1.057850 -0.631944  0.555904  1.097064 -1.387151  0.353236
33   -0.711113 -0.169546  0.171976 -0.212092 -1.132355  1.315146
36    0.829969  0.297953 -0.302928 -0.945781 -0.242724  1.312581
39   -0.697625  1.229031  1.987020  0.343909  2.364586  0.450260
42    1.269170 -1.206863  0.878972  0.837160 -0.437905  0.348167
45   -0.407344 -0.071046  1.459191  1.619865 -0.440274  0.539111
48    0.374244 -0.697430  0.450782 -0.308440  0.228700  0.421094
51   -0.100464  1.401493  0.856901 -1.714850 -0.726944 -0.307432
54    1.227898  0.029258  0.303557  0.058012  0.911842 -0.323239
57    0.260521  0.902231  0.767018 -1.457077 -1.540407  0.214406
60    0.021719 -0.581770 -0.412024  0.199358  1.186086  1.977274
63    0.192915  1.176450 -0.215527  1.906917  0.590545 -1.208706
66    0.617869 -0.012514 -0.028533  0.506198 -0.256584 -0.535241
69    0.675479  1.217800 -0.078125 -1.803885  0.117571  0.667392
72   -0.406723 -0.155374 -1.444615 -0.637595 -1.395026  0.266084
75    0.198348  0.602034 -1.474521  0.306232  3.149443  2.307441
78   -0.793300  0.067512  0.437059 -0.252246  0.623072  0.594353
81   -1.085852  2.311401 -1.244005  0.247349  0.157492 -1.245686
84    0.247839 -0.077916 -0.762923 -0.555147 -0.114645  0.627074
87   -0.681611  0.226183 -0.976978  1.660791 -0.766767  1.677164
90    0.427013  0.126773  0.179123  0.020950  0.268516  0.776483
...        ...       ...       ...       ...       ...       ...
2910 -0.541525  1.038404  0.418874  1.730242  1.382714  0.991357
2913 -0.072480 -0.725895  1.516190 -1.728947 -0.041549  0.139706
2916  0.163878 -0.636558  0.553073 -1.364876  0.496830  0.312249
2919  0.686492  0.094363  0.835299  1.702522  1.135436  1.675020
2922 -0.027295  0.163613 -0.616894 -1.705558  0.762044  0.042091
2925 -2.315108  1.015217  1.062335  1.936149  1.821366  0.648717
2928 -0.411829 -0.732997  1.219275 -0.046593 -0.046027  3.003399
2931 -0.992891  0.501892 -0.630952  0.223819 -0.646514 -1.224562
2934 -0.550826  0.522783 -0.271546  1.439498 -0.013425  0.582987
2937  0.410123 -0.127677 -0.229596 -0.830667  0.071714  0.747561
2940  0.087771  0.252386 -0.959825  0.340264 -2.200490 -0.074453
2943 -3.003522 -1.629006  0.641945 -0.404185  0.716316  0.786389
2946  0.745290 -0.641602  1.073723 -0.448407 -0.046598  0.168012
2949 -2.961654  0.697773 -0.411028 -0.823714  1.253074  0.921263
2952  0.461372  0.963166 -0.387544 -1.167225  0.449699  0.416678
2955  0.643405  0.192321  1.981152  0.603926 -1.279414  1.097114
2958  0.122122  0.813402 -0.739232  0.547289 -1.337955 -1.105406
2961 -0.813555 -0.941517 -0.532860  0.754205 -1.290289 -0.612412
2964 -0.024280  0.542704 -0.594932  0.099559 -0.992261  0.596028
2967 -2.427947  0.160422  0.527004  1.206161  0.998892  0.529822
2970 -0.016148  1.763208 -1.034053  0.872201 -0.758887 -0.753172
2973  1.674303 -0.387506 -2.254331 -1.773518  0.615029 -1.716148
2976  2.119215  0.767200  0.782669 -0.044936  0.923013  0.825720
2979 -0.595234  0.600849  0.316792  0.253311  0.153847 -0.369398
2982 -0.708021 -1.713307 -0.552180 -0.307223 -0.939053 -0.820910
2985 -1.573937  0.308366 -1.662245  0.570210 -0.653210 -0.314402
2988 -1.194555  1.977206  0.754842  0.305322  1.198796  1.473283
2991  1.869433 -0.589284  0.759278 -0.351937 -0.536819  0.777580
2994  0.368289 -0.466715 -0.429377  0.289506 -0.339652 -0.339438
2997 -1.470242  1.698912  0.687847 -0.045696  0.

### Computing With `DataFrames`

You can calculate with `DataFrames` or their columns (which are `Series`) the same way you could with `arrays`s

In [77]:
u['F'] = 1 / u['F']
u['F'].head()

0    -0.816522
3     0.569888
6    -1.327342
9    -2.166337
12    1.060754
Name: F, dtype: float64

In [78]:
np.mean(u)

A   -0.015098
B    0.008872
C   -0.016395
D    0.037659
E    0.037678
F    0.165918
dtype: float64

You can apply functions to the whole dataset or specific columns with the `apply` command. `apply` acts on the whole column at a time (i.e. a Pandas `Series`), so you can compute things that depend on several values of the column, for instance the mean value. To apply functions in a real element-by-element basis the function `applymap` or `Series.apply` should be used.

In [79]:
def mn(col):
    return sum(col) / len(col)

u.apply(mn)

A   -0.015098
B    0.008872
C   -0.016395
D    0.037659
E    0.037678
F    0.165918
dtype: float64

While most can be directly calculated (including the given example of the mean), `apply` also works on columns with strings or categorical data, where no mathematical operations are defined. The limit is the imagination.

### Combining `DataFrames`

Something we will do quite often as scientists is combining data from different sources into one single source. This can be achieved by different commands in Pandas, depending on the actual goal we want.

To begin with, appending new rows of data is achieved by the command `append`.

In [80]:
newdata = pd.DataFrame(np.ones((5, 6)), index=np.arange(3003, 3018, 3), columns=list('ABCDEF'))
newdata

A    B    C    D    E    F
3003  1.0  1.0  1.0  1.0  1.0  1.0
3006  1.0  1.0  1.0  1.0  1.0  1.0
3009  1.0  1.0  1.0  1.0  1.0  1.0
3012  1.0  1.0  1.0  1.0  1.0  1.0
3015  1.0  1.0  1.0  1.0  1.0  1.0

In [81]:
unew = u.append(newdata)
unew.tail(10)

A         B         C         D         E         F
2985 -1.573937  0.308366 -1.662245  0.570210 -0.653210 -3.180637
2988 -1.194555  1.977206  0.754842  0.305322  1.198796  0.678756
2991  1.869433 -0.589284  0.759278 -0.351937 -0.536819  1.286042
2994  0.368289 -0.466715 -0.429377  0.289506 -0.339652 -2.946043
2997 -1.470242  1.698912  0.687847 -0.045696  0.683194  0.528277
3003  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

The same result can be obtained with `concat`.

In [82]:
pd.concat([u, newdata]).tail(10)

A         B         C         D         E         F
2985 -1.573937  0.308366 -1.662245  0.570210 -0.653210 -3.180637
2988 -1.194555  1.977206  0.754842  0.305322  1.198796  0.678756
2991  1.869433 -0.589284  0.759278 -0.351937 -0.536819  1.286042
2994  0.368289 -0.466715 -0.429377  0.289506 -0.339652 -2.946043
2997 -1.470242  1.698912  0.687847 -0.045696  0.683194  0.528277
3003  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

New columns of data can just be asigned or added with the command `join`.

In [83]:
u['G'] = np.random.choice(['a', 'b', 'c'], len(u))
u.tail()

A         B         C         D         E         F  G
2985 -1.573937  0.308366 -1.662245  0.570210 -0.653210 -3.180637  a
2988 -1.194555  1.977206  0.754842  0.305322  1.198796  0.678756  c
2991  1.869433 -0.589284  0.759278 -0.351937 -0.536819  1.286042  a
2994  0.368289 -0.466715 -0.429377  0.289506 -0.339652 -2.946043  c
2997 -1.470242  1.698912  0.687847 -0.045696  0.683194  0.528277  b

### Grouping Data

In [84]:
for h, group in u.groupby('G'):
    print('{}: {}'.format(h, np.mean(group['F'])))

a: 1.957942920266536
b: -1.9937857963520162
c: 0.3156890666121583


In [85]:
u.groupby('G').describe()

A                                                              \
   count      mean       std       min       25%       50%       75%   
G                                                                      
a  356.0  0.000166  1.033033 -2.961654 -0.692794  0.015768  0.698239   
b  318.0  0.004829  0.964332 -3.003522 -0.694332 -0.020203  0.669275   
c  326.0 -0.051205  0.951685 -2.772829 -0.671136 -0.065995  0.601250   

                 B              ...             E                F            \
        max  count      mean    ...           75%       max  count      mean   
G                               ...                                            
a  3.073027  356.0 -0.032244    ...      0.567163  3.149443  356.0  1.957943   
b  3.102455  318.0 -0.035534    ...      0.679460  4.026294  318.0 -1.993786   
c  2.365839  326.0  0.097088    ...      0.821539  3.218986  326.0  0.315689   

                                                                   
         std         min       25%       50%       75%        max  
G                                                                  
a  16.775948  -27.646558 -1.549306  0.358729  1.382375  149.85515  
b  26.693357 -375.840536 -1.373964  0.452339  1.415654  136.67762  
c  20.031013 -199.245125 -1.460392  0.379434  1.618884  221.08552  

[3 rows x 48 columns]

### Loading and saving dataframes

To load and save Pandas dataframes we will use the `to_csv` and `read_csv` commands

In [86]:
u.to_csv('test.csv')
v = pd.read_csv('test.csv', index_col=0)
v.head()

A         B         C         D         E         F  G
0  -2.027348 -0.760066  1.818686 -0.616385  0.552074 -0.816522  a
3  -0.240134 -1.034095  0.678209 -0.204445 -0.439685  0.569888  b
6   0.152990 -0.655726 -1.630595  0.101850 -0.064469 -1.327342  a
9  -0.357923 -1.487928 -1.013571  2.227863  0.939255 -2.166337  c
12  0.304958 -1.514211 -0.053739  0.276051 -0.733645  1.060754  a

But, as an addition, Pandas has special commands to load and save Excel spreadsheets (yay!). However, to use it you'll need the `openpyxl` and `xlrd` packages.

In [87]:
u.to_excel('test.xlsx', sheet_name='My sheet')
pd.read_excel('test.xlsx', 'My sheet', index_col=0).head()

A         B         C         D         E         F  G
0  -2.027348 -0.760066  1.818686 -0.616385  0.552074 -0.816522  a
3  -0.240134 -1.034095  0.678209 -0.204445 -0.439685  0.569888  b
6   0.152990 -0.655726 -1.630595  0.101850 -0.064469 -1.327342  a
9  -0.357923 -1.487928 -1.013571  2.227863  0.939255 -2.166337  c
12  0.304958 -1.514211 -0.053739  0.276051 -0.733645  1.060754  a

**Exercise 5**: Download [this dataset](https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv) and load it, using the first column as the index. Take a look at it, and do the following things:
- Choose the columns 'Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1' and 'Type2' 
- Create a function that lowercases strings and apply it to 'Type1' and 'Type2' (*Extra: just capitalize the strings, i.e., leave the first letter uppercase and lowercase the rest*)
- Create a function that returns a Boolean value (don't be afraif by this, it is a function that returns either True or False) that tells if a Pokémon has high stamina (BaseStamina>170) or not. Store this information in a new column and show the list of Pokémon with high stamina
- Show the instructor the last 15 rows of your dataset

In [88]:
df = pd.read_csv('https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv', 
                 index_col=0)

df = df[['Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1', 'Type2']]

capitalize = lambda st: st.capitalize()

for col in ['Type1', 'Type2']:
    df[col] = df[col].apply(capitalize)
    
def highstamina(x):
    return True if x > 170 else False

df['HighStamina'] = df.BaseStamina.apply(highstamina)

print(df[df['HighStamina'] == True].Identifier)

df.tail(15)

PkMn
31      Nidoqueen
36       Clefable
39     Jigglypuff
40     Wigglytuff
59       Arcanine
62      Poliwrath
68        Machamp
79       Slowpoke
80        Slowbro
87        Dewgong
89            Muk
103     Exeggutor
108     Lickitung
112        Rhydon
113       Chansey
115    Kangaskhan
130      Gyarados
131        Lapras
134      Vaporeon
143       Snorlax
144      Articuno
145        Zapdos
146       Moltres
149     Dragonite
150        Mewtwo
151           Mew
Name: Identifier, dtype: object


Identifier  BaseStamina  BaseAttack  BaseDefense     Type1   Type2  \
PkMn                                                                       
137      Porygon          130         156          158    Normal    None   
138      Omanyte           70         132          160      Rock   Water   
139      Omastar          140         180          202      Rock   Water   
140       Kabuto           60         148          142      Rock   Water   
141     Kabutops          120         190          190      Rock   Water   
142   Aerodactyl          160         182          162      Rock  Flying   
143      Snorlax          320         180          180    Normal    None   
144     Articuno          180         198          242       Ice  Flying   
145       Zapdos          180         232          194  Electric  Flying   
146      Moltres          180         242          194      Fire  Flying   
147      Dratini           82         128          110    Dragon    None   
148    Dragonair          122         170          152    Dragon    None   
149    Dragonite          182         250          212    Dragon  Flying   
150       Mewtwo          212         284          202   Psychic    None   
151          Mew          200         220          220   Psychic    None   

      HighStamina  
PkMn               
137         False  
138         False  
139         False  
140         False  
141         False  
142         False  
143          True  
144          True  
145          True  
146          True  
147         False  
148         False  
149          True  
150          True  
151          True