# 4 NumPy and Pandas

## Introduction

After getting used to how Python works, it is the moment to begin getting our hands dirty with data analysis. We will study two packages: [NumPy](http://www.numpy.org/) is the fundamental numeric computing and linear algebra package in Python, that allows for decent data analysis. We will learn it not only for the data analysis, but more importantly because it will be a package that will be always present in our `import` section as scientists. After NumPy we will go to [Pandas](http://pandas.pydata.org/). Pandas is a dedicated data analysis package with a lot more functionalities than NumPy, making our life much easier in terms of data visualization and manipulation. All the power of Pandas will be completely unleashed in Section 5, where we will see how to visualize information in plots.

As usual, we begin importing the necessary packages

In [1]:
import numpy as np
import pandas as pd
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 1.13.1
Pandas: 0.20.3


## Numeric Python (NumPy)

NumPy is an open-source add-on module to Python that provides common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that
associated with common commercial software like MATLAB. The [NumPy](http://www.numpy.org/) (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. The main object NumPy works with is a *homogeneous multidimensional array*. Despite its intimidating name, these are nothing but tables of numbers, each labelled by a tuple of indices.

We will now explore some capabilities of NumPy that will prove very useful not only for data analyisis, but throughout all our life with Python.

### Creating Arrays

As mentioned before, the main object in NumPy is the *array*. Creating one is as easy as calling the command `array`

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
type(x)

numpy.ndarray

The same applies to multidimensional arrays

In [4]:
m = np.array([[[7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6]]])
m

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

There is one restriction with respect to the use of lists: while you could create lists with data of different type, all the data in an array has to be of the same type, and it will be converted automatically.

In [5]:
lst = [1., 'cat']
print(type(lst[0]))

arr = np.array(lst)
print(type(arr[0]))

<class 'float'>
<class 'numpy.str_'>


(We will go deeper into indexing in a while)

-----
A NumPy array has a number of dimensions (or *axes*). To obtain the number of axes and the size of each of them you use the command `shape`. For 2-dimensional arrays (matrices), the order corresponds to (rows, columns)

There are two different ways of calling the `shape` command, either with `np.shape(arr)` or `arr.shape`. This is not the only command that works in both formats, and we will be finding some more in our way.

In [6]:
print(x.shape)
print(np.shape(m))

(3,)
(2, 2, 3)


### Special Arrays

Now we review some built-in functions that create matrices commonly used. `ones` and `zeros` return arrays of given shape and type (default is float64), filled with ones or zeros, respectively.

In [7]:
array_zeros=np.zeros((3, 2))
array_ones=np.ones((3, 2, 4), dtype=np.int8)

In [8]:
array_zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [9]:
array_ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

`eye(d)` returns a 2-D, dimension-$d$ array with ones on the diagonal and zeros elsewhere.

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

`eye` can also create arrays with ones in upper and lower diagonals. To achieve this, you must call `eye(d, d, k)` where $k$ denotes the diagonal (positive for above the center diagonal, negative for below), or `eye(d, k=num)`

In [11]:
print(np.eye(5, 5, 2))
np.eye(5, k=-1)

[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

`diag`, depending on the input, either extracts a diagonal from a matrix (if the input is a 2-D array), or constructs a diagonal array (if the input is a vector).

In [12]:
np.diag(x, 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [13]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np.diag(y))
np.diag(np.diag(y))

[ 1  6 11 16]


array([[ 1,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 16]])

`arange(begin, end, step)` returns evenly spaced values within a given interval. Note that the beginning point is included, but not the ending.

In [14]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
len(n)

15

**Exercise 1 **: Create an array of the first million of odd numbers, both with `arange` and using loops. Try timing both methods to see which one is faster. For that, use `%timeit`.

In [16]:
%timeit np.arange(0, 2e6, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

1.33 ms ± 78.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
205 ms ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Similarly, `linspace(begin, end, points)` returns evenly spaced numbers over a specified interval. Here, instead of specifying the step, you specify the amount of points you want. Also with `linspace` you include the ending of the interval.

In [17]:
o = np.linspace(0, 30, 15)
o

array([  0.        ,   2.14285714,   4.28571429,   6.42857143,
         8.57142857,  10.71428571,  12.85714286,  15.        ,
        17.14285714,  19.28571429,  21.42857143,  23.57142857,
        25.71428571,  27.85714286,  30.        ])

In [18]:
len(o)

15

`reshape` changes the shape of an array, but not its data. This is another of the commands that can be called before or after the array.

In [19]:
print(n.reshape(3, 5))
np.reshape(n, (5, 3))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

Note however that, in order for these changes to be permanent, you should do a reassignment of the variable

In [20]:
print(n)  # After the reshapings above, the original array stays being the same

n = n.reshape(3, 5)
n   # Now that we have reassigned it is when it definitely changes shape

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### Combining Arrays

The most general command for combining arrays is `concatenate(arrs, d)`. It takes a list of arrays and concatenates them along axis $d$

In [21]:
p = np.ones([2, 2, 2])
p

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [22]:
np.concatenate([p, 2 * p], 0)

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 2.,  2.],
        [ 2.,  2.]],

       [[ 2.,  2.],
        [ 2.,  2.]]])

In [23]:
np.concatenate([p, 2 * p], 1)

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 2.,  2.],
        [ 2.,  2.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 2.,  2.],
        [ 2.,  2.]]])

In [24]:
np.concatenate([p, 2 * p], 2)

array([[[ 1.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.]],

       [[ 1.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.]]])

However, for common combinations there exist special commands. Use `vstack` to stack arrays in sequence vertically (row wise), `hstack` to stack arrays in sequence horizontally (column wise), and `block` to create arrays out of blocks (only available in versions 1.13.0+)

In [25]:
q = np.ones((2, 2))
np.vstack([q, 2 * q])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 2.,  2.],
       [ 2.,  2.]])

In [26]:
np.hstack([q, 2 * q])

array([[ 1.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.]])

In [27]:
np.block([[q, np.zeros((2, 2))], [np.zeros((2, 2)), 2 * q]])

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  2.],
       [ 0.,  0.,  2.,  2.]])

### Operations

You can perform easily element-wise operations on arrays of any shape. Use the typical symbols, +, -, \*, / and \*\* to perform element-wise addition, subtraction, multiplication, division and power.

In [28]:
x = np.array([1, 2, 3])
print(x)
print(x + 10)
print(3 * x)
print(1 / x)
print(x ** (-2 / 3))
print(2 ** x)

[1 2 3]
[11 12 13]
[3 6 9]
[ 1.          0.5         0.33333333]
[ 1.          0.62996052  0.48074986]
[2 4 8]


Also (and obviously) these symbols can be used to operate between two arrays, which must be of the same shape. If this is the case, they also do element-wise operations

In [29]:
y = np.arange(4, 7, 1)
print(x + y)     # [1+4, 2+5, 3+6]
print(x * y)     # [1*4, 2*5, 3*6]
print(x / y)     # [1/4, 2/5, 3/6]
print(x ** y)    # [1**4, 2**5, 3**6]

[5 7 9]
[ 4 10 18]
[ 0.25  0.4   0.5 ]
[  1  32 729]


For doing vector or matrix multiplication, the command to be used is `dot`

In [30]:
x.dot(y) # 1*4 + 2*5 + 3*6

32

With python 3.5 matrix multiplication got it's own operator

In [31]:
x@y

32

In [32]:
X = np.array([[i + j for i in range(3, 6)] for j in range(3)])
Y = np.diag([1, 1], 1) + np.diag([1], -2)

print('{}\n'.format(X))
print(X * Y)
np.dot(X, Y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]

[[0 4 0]
 [0 0 6]
 [5 0 0]]


array([[5, 3, 4],
       [6, 4, 5],
       [7, 5, 6]])

**Exercise 2**: Take a 10x2 matrix representing $(x1,x2)$ coordinates and transform them into polar coordinates $(r,\theta)$.

*Hint 1: the inverse transformation is given by $x1 = r\cos\theta$, $x2 = r\sin\theta$*

*Hint 2: generate random numbers with the functions in numpy.random*

In [33]:
z = np.random.random((10, 2))
x1, x2 = z[:, 0], z[:, 1]
R = np.sqrt(x1 ** 2 + x2 ** 2)
T = np.arctan2(x2, x1)
print(R)
print(T)

[ 0.49187787  0.86147824  0.09652313  1.07134449  0.23563597  0.8080187
  1.02958228  0.97876822  1.17093622  0.724055  ]
[ 1.28205603  0.46005395  1.36401115  0.91389023  1.07227256  0.13162298
  0.95084025  1.37842551  0.98868773  0.07887391]


#### Transposing

Transposition is a very important operation for linear algebra. Although NumPy is capable of correctly doing matrix-vector products correctly regardless of the orientation of the vector, it is not the case for products of matrices

In [34]:
Z = np.arange(0, 12, 1).reshape((4, 3))

In [35]:
np.dot(Z, y)

array([ 17,  62, 107, 152])

In [36]:
np.dot(Z, y.T)

array([ 17,  62, 107, 152])

In [37]:
Z.dot(X)

array([[ 14,  17,  20],
       [ 50,  62,  74],
       [ 86, 107, 128],
       [122, 152, 182]])

In [38]:
(Z.T).dot(X)

ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

#### Array Methods

To not have to go from NumPy arrays to lists back and forth, NumPy contains some functions to know properties of your arrays. Actually, there are more of these functions than in standard Python.

In [39]:
a = np.array([-4, -2, 1, 3, 5])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

5
-4
3
0.6
3.26190128606


Some interesting functions are `argmax` and `argmin`, which return the index of the maximum and minimum values in the array.

In [40]:
print(a.argmax())
print(a.argmin())

4
0


### Indexing/Slicing

We have already seen briefly that to access individual elements you use the bracket notation: `array[ax_0, ax_1, ...]`, where the `ax_i` denotes the coordinate in the `i`-th axis. You can even use this to assign new values to your elements.

In [41]:
r = [4, 5, 6, 7]
print(r[2])
r[0] = 198
r

6


[198, 5, 6, 7]

To select a range of rows or columns you can use a colon :. A second : can be used to indicate the step size. `array[start:stop:stepsize]`. If you leave `start` (`stop`) blank, the selection will go from the very beginning (until the very end) of the array

In [42]:
s = np.arange(13)**2
print(s)
print(s[3:9])
print(s[2:10:3])
s[-5::-2]

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[ 9 16 25 36 49 64]
[ 4 25 64]


array([64, 36, 16,  4,  0])

The same applies to matrices or higher-dimensional arrays

In [43]:
r = np.arange(36).reshape((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [44]:
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

You can also select specific rows and columns, separated by commas

In [45]:
r[[1, 3, 4], 1:3]

array([[ 7,  8],
       [19, 20],
       [25, 26]])

A very useful tool is *conditional indexing*, where we apply a function, assignment... only to those elements of an array that satisfy some condition

In [46]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Exercise 3**: Create a random 1-dimensional array, and find which element is closest to 0.7

In [47]:
Z = np.random.uniform(0,1,100)
z = 0.7
m = Z[np.abs(Z - z).argmin()]
print(m)

0.706215519643


#### Copying Data

**Be very careful with copying and modifying arrays in NumPy!** You will see the reason right now. Let's begin defining `r2` as a slice of r

In [48]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

And now let's set all its elements to zero

In [49]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

When looking at `r`, we see that it has also been changed!

In [50]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

The proper way of handling selections without modifying the original arrays is through the `copy` command.

In [51]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now we can safely modify `r_copy` without affecting `r`.

In [52]:
r_copy[:] = 10
print('{}\n'.format(r_copy))
r

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]



array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Iterating Over Arrays

Finally, you can iterate over arrays in the same way as you iterate over lists

In [53]:
test = np.random.randint(0, 10, (4,3))
test

array([[6, 2, 3],
       [4, 3, 9],
       [7, 1, 7],
       [9, 1, 5]])

You can iterate by row:

In [54]:
for row in test:
    print(row)

[6 2 3]
[4 3 9]
[7 1 7]
[9 1 5]


Or by row index

In [55]:
for i in range(len(test)):
    print(test[i])

[6 2 3]
[4 3 9]
[7 1 7]
[9 1 5]


Or by row and index:

In [56]:
for i, row in enumerate(test):
    print('Row {} is {}'.format(i, row))

Row 0 is [6 2 3]
Row 1 is [4 3 9]
Row 2 is [7 1 7]
Row 3 is [9 1 5]


In the same way as with lists, you can use `zip` to iterate over multiple iterables.

In [57]:
test2 = test**2
test2

array([[36,  4,  9],
       [16,  9, 81],
       [49,  1, 49],
       [81,  1, 25]])

In [58]:
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[6 2 3] + [36  4  9] = [42  6 12]
[4 3 9] + [16  9 81] = [20 12 90]
[7 1 7] + [49  1 49] = [56  2 56]
[9 1 5] + [81  1 25] = [90  2 30]


**Exercise 4**: Create a function that iterates over the columns of a 2-dimensional array

In [59]:
def iterate(df):
    for i, row in enumerate(df):
        shp = row.shape
        row.shape = shp + (1,)
        print('Column {} is {}'.format(i, row))

iterate(test.T)

Column 0 is [[6]
 [4]
 [7]
 [9]]
Column 1 is [[2]
 [3]
 [1]
 [1]]
Column 2 is [[3]
 [9]
 [7]
 [5]]


### Loading and Saving Data

To load and save data NumPy has the `loadtxt` and `savetxt` commands. However, they only work for two-dimensional arrays

In [60]:
np.savetxt('numpytest.txt', test)
np.loadtxt('numpytest.txt')

array([[ 6.,  2.,  3.],
       [ 4.,  3.,  9.],
       [ 7.,  1.,  7.],
       [ 9.,  1.,  5.]])

## Pandas

When dealing with numeric matrices and vectors in Python, NumPy makes life a lot easier. For more complex data, however, it leaves a bit to be desired. For those used to working with dedicated languages like R, doing data analysis directly with numpy feels like a step back. Fortunately, some nice folks have written the Python Data Analysis Library (a.k.a. [pandas](http://pandas.pydata.org/)). Pandas provides an R-like DataFrame, produces high quality plots with matplotlib, and integrates nicely with other libraries that expect NumPy arrays.

Pandas works with `Series` of data, that then are arranged in `DataFrame`s. A dataframe will be the object closest to an Excel spreadsheet that you will see throughout the course (but of course, given that it is integrated in Python and can be combined with so many different packages, dataframes are much more powerful than Excel spreadsheets). The data in the series can be either qualitative or quantitative data. Creating a series is as easy as creating a NumPy array from a one-dimensional list.

In [61]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [62]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

Notice that the series is indexed by default by integers. You can change this indexing by using a dictionary instead of a list for creating the series.

In [63]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

On the other hand, `DataFrame`s can be built from two-dimensional arrays, with the ability of labelling columns and indexing the rows

In [64]:
u = pd.DataFrame(np.random.randn(1000,6), index=np.arange(0, 3000, 3), columns=['A', 'B', 'C', 'D', 'E', 'F'])
u

A         B         C         D         E         F
0    -0.486390  1.006064  0.321450  0.539001  0.967269  0.826700
3     2.400124  0.357823  0.400378  1.625708  0.272849 -0.415272
6    -0.485364  0.058415 -0.289454  1.695473 -0.519594 -0.116215
9     0.126916  1.599085  1.027031 -0.966302 -0.312185 -1.000940
12    1.656042  0.746992  0.581831 -0.269498 -0.885463 -1.678499
15   -0.599577  1.150801 -1.374039 -2.478844  0.375244 -1.147043
18   -0.912522  0.355907 -1.080131 -1.374392 -0.733674 -0.442884
21   -0.875569 -0.473255 -0.547435  0.793215 -0.107531  0.862464
24    1.533748  1.179712 -1.677763 -0.471846 -0.897669 -0.454207
27   -0.051302  2.127357  0.801260 -1.002258  0.856915 -0.278422
30    0.890435 -0.629608 -0.538587  0.151643  0.078088 -0.671726
33    0.898467  1.372391  0.844704 -1.623268 -0.143715 -0.030636
36    0.968105  1.209681 -1.024959  2.014902 -0.837118  1.971436
39    0.752046 -1.135508 -1.143866 -1.158633  0.041458  1.400493
42    0.807033  0.264685  0.529943  0.385121 -1.476369 -0.989553
45   -0.968112  0.838967 -0.525675  0.037711  0.739999  0.387780
48   -0.004151  0.929277  0.354432  1.369246  1.645019  1.615283
51    2.791861  0.018670 -1.053684  0.497809  1.744013 -0.944426
54    0.421063  1.586485  1.210293  0.635509  0.902434 -0.895842
57    0.544965 -0.510496  0.076188  0.230262  1.613266 -1.164069
60    0.014930  0.397993  0.224944 -1.509285  0.940167  1.365971
63    0.219509  0.505074 -0.100002  1.792895  0.225734 -1.272991
66    1.787977 -1.535172  1.218502 -0.965560  0.337063  0.285236
69    1.200903 -1.594836  0.334670  0.488374  0.880156  0.646622
72   -0.858045 -0.885338 -0.219164  2.018379  1.082300 -0.168884
75    0.141045  1.318812 -0.451973  2.118345 -0.776782  0.430845
78   -0.434456  0.859744 -0.267306 -0.250474  1.284816  0.139293
81   -0.471995  0.461743 -0.933235  1.086010  1.156255  0.011029
84    0.338068  0.569003  0.475323  0.132249 -0.928181 -0.219376
87   -1.341857 -0.174481 -1.916150  1.251773  2.121511 -1.343819
...        ...       ...       ...       ...       ...       ...
2910 -0.103908  0.172065  0.865109  0.570274 -0.794574 -0.721609
2913  1.941453 -0.172584  0.819111 -1.518545 -0.971808  1.140873
2916 -1.002884  2.646222  1.682343  0.719269 -0.348128  0.110747
2919  0.128021  1.334755 -0.085092  0.474602 -0.493769  0.107727
2922 -0.875423  0.460520 -0.779785  0.284604  0.858395 -0.322807
2925 -0.357314 -0.957049 -1.728277  0.314301  1.496883  0.680951
2928  0.571785  0.712115 -0.953699 -0.217702  0.736807  1.118588
2931 -1.123076 -0.746646 -1.233317 -1.524507  0.771299 -0.463037
2934 -0.164677 -0.956259 -0.413584 -0.136122  0.285828  0.622753
2937 -0.783937  0.011081 -0.380387 -1.897177  0.672644  0.255565
2940  0.302601 -1.203350 -0.348406  1.572813  1.718035  1.833360
2943 -0.165133  1.164564  1.274052 -0.225683 -0.074910 -0.017333
2946 -0.180485 -0.328879 -2.020654  0.049166  1.354548 -0.812376
2949 -1.805850 -0.029158  0.984106 -0.601257  0.159671 -0.087560
2952 -0.871729 -0.869082 -0.097081 -0.098217  0.144713  0.177416
2955  0.304855 -0.730931  0.385327  0.511779  0.322430  0.044808
2958 -0.731189  0.209960  0.479687  0.831041 -0.358416 -0.288705
2961 -0.449455 -1.543244 -1.839800 -0.901192 -0.577996 -0.466067
2964 -1.545436 -0.005503 -0.941426  0.091104 -0.733067  0.833001
2967 -0.103569  1.004182  1.423020 -1.106816 -0.491260  0.758803
2970 -0.953438 -0.595328  0.810105  0.281188 -0.441127 -0.077448
2973 -2.824601 -0.484782 -0.110566  1.300086 -0.078114  0.006849
2976  1.121195  0.130817 -1.094877  0.222777 -0.292675 -1.336767
2979  2.024362  1.572801  1.819986 -0.799127  0.277014  0.025134
2982  0.599294  1.025102 -1.433774 -3.430698  0.610022  0.375678
2985 -0.049410 -0.421436 -0.118905  0.845203  0.424697  0.591122
2988  0.385888 -0.141475  0.282936 -0.553130  0.087001  0.146126
2991 -0.051031 -0.339346 -1.124901  0.120227 -0.086591  0.109190
2994 -0.150851  0.171049  0.301247  0.653709  0.049595  1.170720
2997 -1.529875 -1.813296 -1.989128  1.279956 -0.

As you might have noticed, it is a bit ugly to deal with large dataframes. There are however some functions that allows to have an idea of the data in a frame.

In [65]:
u.head()

A         B         C         D         E         F
0  -0.486390  1.006064  0.321450  0.539001  0.967269  0.826700
3   2.400124  0.357823  0.400378  1.625708  0.272849 -0.415272
6  -0.485364  0.058415 -0.289454  1.695473 -0.519594 -0.116215
9   0.126916  1.599085  1.027031 -0.966302 -0.312185 -1.000940
12  1.656042  0.746992  0.581831 -0.269498 -0.885463 -1.678499

In [66]:
u.tail()

A         B         C         D         E         F
2985 -0.049410 -0.421436 -0.118905  0.845203  0.424697  0.591122
2988  0.385888 -0.141475  0.282936 -0.553130  0.087001  0.146126
2991 -0.051031 -0.339346 -1.124901  0.120227 -0.086591  0.109190
2994 -0.150851  0.171049  0.301247  0.653709  0.049595  1.170720
2997 -1.529875 -1.813296 -1.989128  1.279956 -0.511653  1.587069

In [67]:
u.describe()

A            B            C            D            E  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.003606     0.072535    -0.034625    -0.021335    -0.012738   
std       1.022266     1.005751     1.008314     1.034881     1.019030   
min      -3.727366    -3.377907    -3.640897    -3.430698    -3.318951   
25%      -0.682101    -0.607918    -0.730713    -0.706849    -0.702791   
50%      -0.004479     0.111144    -0.033035     0.011561     0.000659   
75%       0.748163     0.747249     0.667122     0.641024     0.694101   
max       2.791861     3.291482     3.810366     3.144464     2.999393   

                 F  
count  1000.000000  
mean      0.028699  
std       1.007661  
min      -3.234716  
25%      -0.676170  
50%       0.074180  
75%       0.733811  
max       2.877106

### Indexing/Slicing in Pandas

The easiest way of accessing information in a Pandas dataframe, equivalent to the way used in NumPy, is using the `iloc` command. With this you can also set specific values, do conditional indexing... all that we have seen before in section 2.4

In [68]:
u.iloc[125:132,[0, 2, 5]]

A         C         F
375  0.087548 -1.038510  1.562728
378  0.170242 -0.706325 -1.905718
381  0.254539  0.256863 -0.274089
384  0.007908  1.359674 -0.353677
387  0.462825  0.883289 -0.594398
390  0.565687  0.750447 -1.254893
393  0.883862 -0.090684  1.961763

However, there are a few different ways of accessing the data in a Pandas dataframe, that typically have a more "direct" connection with the actual content fo the dataframe. Individual or sets of columns can also be accessed by their column names. Choosing one single column will give a Series, while two or more will produce a Dataset

In [69]:
u['A'].head()

0    -0.486390
3     2.400124
6    -0.485364
9     0.126916
12    1.656042
Name: A, dtype: float64

In [70]:
u[['A', 'D']].head()

A         D
0  -0.486390  0.539001
3   2.400124  1.625708
6  -0.485364  1.695473
9   0.126916 -0.966302
12  1.656042 -0.269498

Not only that, you can access a single column without the need of brackets []

In [71]:
u.A.head()

0    -0.486390
3     2.400124
6    -0.485364
9     0.126916
12    1.656042
Name: A, dtype: float64

The usual [] will select specific rows according to the row number

In [72]:
u[0:10][list('BCF')]

B         C         F
0   1.006064  0.321450  0.826700
3   0.357823  0.400378 -0.415272
6   0.058415 -0.289454 -0.116215
9   1.599085  1.027031 -1.000940
12  0.746992  0.581831 -1.678499
15  1.150801 -1.374039 -1.147043
18  0.355907 -1.080131 -0.442884
21 -0.473255 -0.547435  0.862464
24  1.179712 -1.677763 -0.454207
27  2.127357  0.801260 -0.278422

You can also choose specific rows according to their indices with the `loc` command

In [73]:
u.loc[6:15]

A         B         C         D         E         F
6  -0.485364  0.058415 -0.289454  1.695473 -0.519594 -0.116215
9   0.126916  1.599085  1.027031 -0.966302 -0.312185 -1.000940
12  1.656042  0.746992  0.581831 -0.269498 -0.885463 -1.678499
15 -0.599577  1.150801 -1.374039 -2.478844  0.375244 -1.147043

Or, you can access just the elements that satisfy some condition

In [74]:
u[u.D > 2]

A         B         C         D         E         F
36    0.968105  1.209681 -1.024959  2.014902 -0.837118  1.971436
72   -0.858045 -0.885338 -0.219164  2.018379  1.082300 -0.168884
75    0.141045  1.318812 -0.451973  2.118345 -0.776782  0.430845
297  -0.139421  1.642056  0.444386  2.607057 -1.524716 -1.102453
369  -0.939105 -0.659259  1.038402  2.338393 -1.444747  0.219624
396  -1.258892  0.522062  0.118400  2.317091 -1.975992  2.088000
423   0.829726  0.384305 -0.255447  2.590151  0.318381  0.321130
747   0.180803 -0.168061  1.024848  3.144464 -0.531328  0.468991
906  -0.579028 -0.812402  1.928433  2.189363 -1.870593 -0.080945
972   0.508881  0.316569 -2.398584  2.345536  0.655461  1.621037
1155  1.377076  0.121989  1.531763  2.097647  1.495285  0.662651
1200  0.237674  0.553704  1.311406  2.021933  1.655326  0.560579
1284  0.613719 -1.069622 -0.356617  2.902930 -1.882570  1.125197
1410 -0.692410  1.249636 -0.468295  2.504633  0.344653 -0.983399
1542 -1.218466 -1.307905  1.439579  2.030202  0.880691  0.349449
1545 -0.795326  1.637831 -0.720797  3.071453 -1.174544 -1.143020
1674  0.226720 -0.832528 -0.010493  2.920399  1.311452  0.152185
1692 -0.318562  0.882907 -0.053103  2.457979  0.356630 -0.639370
1797  0.035744  1.235725 -0.524402  2.152208 -0.637144 -1.017276
1902 -0.499741  0.470271  0.721999  2.071643  0.319955  1.012490
2055 -0.721962  0.444672 -3.640897  2.382251 -2.313719 -0.948939
2223  0.861751 -2.388922  0.976400  2.361192 -1.012845  0.524826
2286 -2.072057 -0.677751 -0.464646  2.089259  0.532221  0.984135
2517  0.088943  0.796699 -1.154465  2.123651 -1.236171  1.770905
2619 -0.265623  1.969601 -0.122572  2.024209  0.518032  0.961724
2757  1.809499 -1.334946  0.617888  2.061619 -1.505878 -0.165551
2796  0.771429 -1.033978 -1.039393  2.829567  0.023117  1.111027
2838  1.101989 -0.439136  1.201865  2.172643 -0.606109  1.663842

### Applying Functions

An interesting capability of Pandas is that you can apply functions to the whole dataset or specific columns with the `apply` command

In [75]:
def func(x):
    return 1 / x

u['F'] = u['F'].apply(func)
u['F'].head()

0     1.209629
3    -2.408059
6    -8.604762
9    -0.999061
12   -0.595770
Name: F, dtype: float64

`apply` acts on the whole column at a time, so you can compute things that depend on several values of the column, for instance the mean value. To apply functions in a real element-by-element basis the function `applymap` should be used.

In [76]:
def mn(col):
    return sum(col) / len(col)

u.apply(mn)

A    0.003606
B    0.072535
C   -0.034625
D   -0.021335
E   -0.012738
F    4.031046
dtype: float64

Functions can also be applied to columns with strings or categorical data. The limit is the imagination.


### Combining `DataFrames`

Something we will do quite often as scientists is combining data from different sources into one single source. This can be achieved by different commands in Pandas, depending on the actual goal we want.

To begin with, appending new rows of data is achieved by the command `append`.

In [77]:
newdata = pd.DataFrame(np.ones((5, 6)), index=np.arange(3003, 3018, 3), columns=list('ABCDEF'))
newdata

A    B    C    D    E    F
3003  1.0  1.0  1.0  1.0  1.0  1.0
3006  1.0  1.0  1.0  1.0  1.0  1.0
3009  1.0  1.0  1.0  1.0  1.0  1.0
3012  1.0  1.0  1.0  1.0  1.0  1.0
3015  1.0  1.0  1.0  1.0  1.0  1.0

In [78]:
unew = u.append(newdata)
unew.tail(10)

A         B         C         D         E         F
2985 -0.049410 -0.421436 -0.118905  0.845203  0.424697  1.691699
2988  0.385888 -0.141475  0.282936 -0.553130  0.087001  6.843422
2991 -0.051031 -0.339346 -1.124901  0.120227 -0.086591  9.158365
2994 -0.150851  0.171049  0.301247  0.653709  0.049595  0.854175
2997 -1.529875 -1.813296 -1.989128  1.279956 -0.511653  0.630092
3003  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

The same result can be obtained with `concat`.

In [79]:
pd.concat([u, newdata]).tail(10)

A         B         C         D         E         F
2985 -0.049410 -0.421436 -0.118905  0.845203  0.424697  1.691699
2988  0.385888 -0.141475  0.282936 -0.553130  0.087001  6.843422
2991 -0.051031 -0.339346 -1.124901  0.120227 -0.086591  9.158365
2994 -0.150851  0.171049  0.301247  0.653709  0.049595  0.854175
2997 -1.529875 -1.813296 -1.989128  1.279956 -0.511653  0.630092
3003  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

New columns of data can just be asigned or added with the command `join`.

In [80]:
u['G'] = 666
newcol = pd.Series(np.ones(1000,) * 1337, name='H')
u.join(newcol).head()

A         B         C         D         E         F    G       H
0  -0.486390  1.006064  0.321450  0.539001  0.967269  1.209629  666  1337.0
3   2.400124  0.357823  0.400378  1.625708  0.272849 -2.408059  666  1337.0
6  -0.485364  0.058415 -0.289454  1.695473 -0.519594 -8.604762  666  1337.0
9   0.126916  1.599085  1.027031 -0.966302 -0.312185 -0.999061  666  1337.0
12  1.656042  0.746992  0.581831 -0.269498 -0.885463 -0.595770  666  1337.0

### Loading and saving dataframes

To load and save Pandas dataframes we will use the `to_csv` and `read_csv` commands

In [81]:
u.to_csv('test.csv')
v = pd.read_csv('test.csv', index_col=0)
v.head()

A         B         C         D         E         F    G
0  -0.486390  1.006064  0.321450  0.539001  0.967269  1.209629  666
3   2.400124  0.357823  0.400378  1.625708  0.272849 -2.408059  666
6  -0.485364  0.058415 -0.289454  1.695473 -0.519594 -8.604762  666
9   0.126916  1.599085  1.027031 -0.966302 -0.312185 -0.999061  666
12  1.656042  0.746992  0.581831 -0.269498 -0.885463 -0.595770  666

But, as an addition, Pandas has special commands to load and save Excel spreadsheets (yay!). However, to use it you'll need the `openpyxl` and `xlrd` packages.

In [82]:
u.to_excel('test.xlsx', sheet_name='My sheet')
pd.read_excel('test.xlsx', 'My sheet', index_col=0).head()

A         B         C         D         E         F    G
0  -0.486390  1.006064  0.321450  0.539001  0.967269  1.209629  666
3   2.400124  0.357823  0.400378  1.625708  0.272849 -2.408059  666
6  -0.485364  0.058415 -0.289454  1.695473 -0.519594 -8.604762  666
9   0.126916  1.599085  1.027031 -0.966302 -0.312185 -0.999061  666
12  1.656042  0.746992  0.581831 -0.269498 -0.885463 -0.595770  666

**Exercise 5**: Download [this dataset](https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv) and load it, using the first column as the index. Take a look at it, and do the following things:
- Choose the columns 'Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1' and 'Type2' 
- Create a function that lowercases strings and apply it to 'Type1' and 'Type2' (*Extra: just capitalize the strings, i.e., leave the first letter uppercase and lowercase the rest*)
- Create a function that returns a Boolean value (don't be afraif by this, it is a function that returns either True or False) that tells if a Pokémon has high stamina (BaseStamina>170) or not. Store this information in a new column and show the list of Pokémon with high stamina
- Show the instructor the last 15 rows of your dataset

In [83]:
df = pd.read_csv('https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv', index_col=0)

df = df[['Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1', 'Type2']]

capitalize = lambda st: st.capitalize()

for col in ['Type1', 'Type2']:
    df[col] = df[col].apply(capitalize)
    
def highstamina(x):
    return True if x > 170 else False

df['HighStamina'] = df.BaseStamina.apply(highstamina)

print(df[df['HighStamina'] == True].Identifier)

df.tail(15)

PkMn
31      Nidoqueen
36       Clefable
39     Jigglypuff
40     Wigglytuff
59       Arcanine
62      Poliwrath
68        Machamp
79       Slowpoke
80        Slowbro
87        Dewgong
89            Muk
103     Exeggutor
108     Lickitung
112        Rhydon
113       Chansey
115    Kangaskhan
130      Gyarados
131        Lapras
134      Vaporeon
143       Snorlax
144      Articuno
145        Zapdos
146       Moltres
149     Dragonite
150        Mewtwo
151           Mew
Name: Identifier, dtype: object


Identifier  BaseStamina  BaseAttack  BaseDefense     Type1   Type2  \
PkMn                                                                       
137      Porygon          130         156          158    Normal    None   
138      Omanyte           70         132          160      Rock   Water   
139      Omastar          140         180          202      Rock   Water   
140       Kabuto           60         148          142      Rock   Water   
141     Kabutops          120         190          190      Rock   Water   
142   Aerodactyl          160         182          162      Rock  Flying   
143      Snorlax          320         180          180    Normal    None   
144     Articuno          180         198          242       Ice  Flying   
145       Zapdos          180         232          194  Electric  Flying   
146      Moltres          180         242          194      Fire  Flying   
147      Dratini           82         128          110    Dragon    None   
148    Dragonair          122         170          152    Dragon    None   
149    Dragonite          182         250          212    Dragon  Flying   
150       Mewtwo          212         284          202   Psychic    None   
151          Mew          200         220          220   Psychic    None   

      HighStamina  
PkMn               
137         False  
138         False  
139         False  
140         False  
141         False  
142         False  
143          True  
144          True  
145          True  
146          True  
147         False  
148         False  
149          True  
150          True  
151          True

In [84]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv', index_col=0)

df = df[['Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1', 'Type2']]

In [85]:
df[~(df.BaseStamina > 170)]

Identifier  BaseStamina  BaseAttack  BaseDefense     Type1    Type2
PkMn                                                                     
1      Bulbasaur           90         126          126     GRASS   POISON
2        Ivysaur          120         156          158     GRASS   POISON
3       Venusaur          160         198          200     GRASS   POISON
4     Charmander           78         128          108      FIRE     NONE
5     Charmeleon          116         160          140      FIRE     NONE
6      Charizard          156         212          182      FIRE   FLYING
7       Squirtle           88         112          142     WATER     NONE
8      Wartortle          118         144          176     WATER     NONE
9      Blastoise          158         186          222     WATER     NONE
10      Caterpie           90          62           66       BUG     NONE
11       Metapod          100          56           86       BUG     NONE
12    Butterfree          120         144          144       BUG   FLYING
13        Weedle           80          68           64       BUG   POISON
14        Kakuna           90          62           82       BUG   POISON
15      Beedrill          130         144          130       BUG   POISON
16        Pidgey           80          94           90    NORMAL   FLYING
17     Pidgeotto          126         126          122    NORMAL   FLYING
18       Pidgeot          166         170          166    NORMAL   FLYING
19       Rattata           60          92           86    NORMAL     NONE
20      Raticate          110         146          150    NORMAL     NONE
21       Spearow           80         102           78    NORMAL   FLYING
22        Fearow          130         168          146    NORMAL   FLYING
23         Ekans           70         112          112    POISON     NONE
24         Arbok          120         166          166    POISON     NONE
25       Pikachu           70         124          108  ELECTRIC     NONE
26        Raichu          120         200          154  ELECTRIC     NONE
27     Sandshrew          100          90          114    GROUND     NONE
28     Sandslash          150         150          172    GROUND     NONE
29       Nidoran          110         100          104    POISON     NONE
30      Nidorina          140         132          136    POISON     NONE
...          ...          ...         ...          ...       ...      ...
109      Koffing           80         136          142    POISON     NONE
110      Weezing          130         190          198    POISON     NONE
111      Rhyhorn          160         110          116    GROUND     ROCK
114      Tangela          130         164          152     GRASS     NONE
116       Horsea           60         122          100     WATER     NONE
117       Seadra          110         176          150     WATER     NONE
118      Goldeen           90         112          126     WATER     NONE
119      Seaking          160         172          160     WATER     NONE
120       Staryu           60         130          128     WATER     NONE
121      Starmie          120         194          192     WATER  PSYCHIC
122         Mime           80         154          196   PSYCHIC    FAIRY
123      Scyther          140         176          180       BUG   FLYING
124         Jynx          130         172          134       ICE  PSYCHIC
125   Electabuzz          130         198          160  ELECTRIC     NONE
126       Magmar          130         214          158      FIRE     NONE
127       Pinsir          130         184          186       BUG     NONE
128       Tauros          150         148          184    NORMAL     NONE
129     Magikarp           40          42           84     WATER     NONE
132        Ditto           96         110          110    NORMAL     NONE
133        Eevee          110         114          128    NORMAL     NONE
135      Jolteon          130         192          174  ELECTRIC     NONE
136      F