# 4 NumPy and Pandas

## Introduction

After getting used to how Python works, it is the moment to begin getting our hands dirty with data analysis. We will study two packages: [NumPy](http://www.numpy.org/) is the fundamental numeric computing and linear algebra package in Python, that allows for decent data analysis. We will learn it not only for the data analysis, but more importantly because it will be a package that will be always present in our `import` section as scientists. After NumPy we will go to [Pandas](http://pandas.pydata.org/). Pandas is a dedicated data analysis package with a lot more functionalities than NumPy, making our life much easier in terms of data visualization and manipulation. All the power of Pandas will be completely unleashed in Section 5, where we will see how to visualize information in plots.

As usual, we begin importing the necessary packages

In [2]:
import numpy as np
import pandas as pd
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 1.13.1
Pandas: 0.20.3


## Numeric Python (NumPy)

NumPy is an open-source add-on module to Python that provides common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that
associated with common commercial software like MATLAB. The [NumPy](http://www.numpy.org/) (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. The main object NumPy works with is a *homogeneous multidimensional array*. Despite its intimidating name, these are nothing but tables of numbers, each labelled by a tuple of indices.

We will now explore some capabilities of NumPy that will prove very useful not only for data analyisis, but throughout all our life with Python.

### Creating Arrays

As mentioned before, the main object in NumPy is the *array*. Creating one is as easy as calling the command `array`

In [3]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

The same applies to multidimensional arrays

In [5]:
m = np.array([[[7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6]]])
m

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

There is one restriction with respect to the use of lists: while you could create lists with data of different type, all the data in an array has to be of the same type, and it will be converted automatically.

In [6]:
lst = [1., 'cat']
print(type(lst[0]))

arr = np.array(lst)
print(type(arr[0]))

<class 'float'>
<class 'numpy.str_'>


(We will go deeper into indexing in a while)

-----
A NumPy array has a number of dimensions (or *axes*). To obtain the number of axes and the size of each of them you use the command `shape`. For 2-dimensional arrays (matrices), the order corresponds to (rows, columns)

There are two different ways of calling the `shape` command, either with `np.shape(arr)` or `arr.shape`. This is not the only command that works in both formats, and we will be finding some more in our way.

In [7]:
print(x.shape)
print(np.shape(m))

(3,)
(2, 2, 3)


### Special Arrays

Now we review some built-in functions that create matrices commonly used. `ones` and `zeros` return arrays of given shape and type (default is float64), filled with ones or zeros, respectively.

In [8]:
array_zeros=np.zeros((3, 2))
array_ones=np.ones((3, 2, 4), dtype=np.int8)

In [9]:
array_zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [10]:
array_ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

`eye(d)` returns a 2-D, dimension-$d$ array with ones on the diagonal and zeros elsewhere.

In [11]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

`eye` can also create arrays with ones in upper and lower diagonals. To achieve this, you must call `eye(d, d, k)` where $k$ denotes the diagonal (positive for above the center diagonal, negative for below), or `eye(d, k=num)`

In [12]:
print(np.eye(5, 5, 2))
np.eye(5, k=-1)

[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

`diag`, depending on the input, either extracts a diagonal from a matrix (if the input is a 2-D array), or constructs a diagonal array (if the input is a vector).

In [13]:
np.diag(x, 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [14]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np.diag(y))
np.diag(np.diag(y))

[ 1  6 11 16]


array([[ 1,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 16]])

`arange(begin, end, step)` returns evenly spaced values within a given interval. Note that the beginning point is included, but not the ending.

In [15]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
len(n)

15

**Exercise 1 **: Create an array of the first million of odd numbers, both with `arange` and using loops. Try timing both methods to see which one is faster. For that, use `%timeit`.

In [17]:
%timeit np.arange(0, 2e6, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

3.06 ms ± 6.02 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
196 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Similarly, `linspace(begin, end, points)` returns evenly spaced numbers over a specified interval. Here, instead of specifying the step, you specify the amount of points you want. Also with `linspace` you include the ending of the interval.

In [18]:
o = np.linspace(0, 30, 15)
o

array([  0.        ,   2.14285714,   4.28571429,   6.42857143,
         8.57142857,  10.71428571,  12.85714286,  15.        ,
        17.14285714,  19.28571429,  21.42857143,  23.57142857,
        25.71428571,  27.85714286,  30.        ])

In [19]:
len(o)

15

`reshape` changes the shape of an array, but not its data. This is another of the commands that can be called before or after the array.

In [20]:
print(n.reshape(3, 5))
np.reshape(n, (5, 3))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

Note however that, in order for these changes to be permanent, you should do a reassignment of the variable

In [21]:
print(n)  # After the reshapings above, the original array stays being the same

n = n.reshape(3, 5)
n   # Now that we have reassigned it is when it definitely changes shape

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### Combining Arrays

The most general command for combining arrays is `concatenate(arrs, d)`. It takes a list of arrays and concatenates them along axis $d$

In [22]:
p = np.ones([2, 2, 2])
p

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [23]:
np.concatenate([p, 2 * p], 0)

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 2.,  2.],
        [ 2.,  2.]],

       [[ 2.,  2.],
        [ 2.,  2.]]])

In [24]:
np.concatenate([p, 2 * p], 1)

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 2.,  2.],
        [ 2.,  2.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 2.,  2.],
        [ 2.,  2.]]])

In [25]:
np.concatenate([p, 2 * p], 2)

array([[[ 1.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.]],

       [[ 1.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.]]])

However, for common combinations there exist special commands. Use `vstack` to stack arrays in sequence vertically (row wise), `hstack` to stack arrays in sequence horizontally (column wise), and `block` to create arrays out of blocks (only available in versions 1.13.0+)

In [26]:
q = np.ones((2, 2))
np.vstack([q, 2 * q])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 2.,  2.],
       [ 2.,  2.]])

In [27]:
np.hstack([q, 2 * q])

array([[ 1.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.]])

In [28]:
np.block([[q, np.zeros((2, 2))], [np.zeros((2, 2)), 2 * q]])

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  2.],
       [ 0.,  0.,  2.,  2.]])

### Operations

You can perform easily element-wise operations on arrays of any shape. Use the typical symbols, +, -, \*, / and \*\* to perform element-wise addition, subtraction, multiplication, division and power.

In [29]:
x = np.array([1, 2, 3])
print(x)
print(x + 10)
print(3 * x)
print(1 / x)
print(x ** (-2 / 3))
print(2 ** x)

[1 2 3]
[11 12 13]
[3 6 9]
[ 1.          0.5         0.33333333]
[ 1.          0.62996052  0.48074986]
[2 4 8]


Also (and obviously) these symbols can be used to operate between two arrays, which must be of the same shape. If this is the case, they also do element-wise operations

In [30]:
y = np.arange(4, 7, 1)
print(x + y)     # [1+4, 2+5, 3+6]
print(x * y)     # [1*4, 2*5, 3*6]
print(x / y)     # [1/4, 2/5, 3/6]
print(x ** y)    # [1**4, 2**5, 3**6]

[5 7 9]
[ 4 10 18]
[ 0.25  0.4   0.5 ]
[  1  32 729]


For doing vector or matrix multiplication, the command to be used is `dot`

In [31]:
x.dot(y) # 1*4 + 2*5 + 3*6

32

With python 3.5 matrix multiplication got it's own operator

In [32]:
x@y

32

In [33]:
X = np.array([[i + j for i in range(3, 6)] for j in range(3)])
Y = np.diag([1, 1], 1) + np.diag([1], -2)

print('{}\n'.format(X))
print(X * Y)
np.dot(X, Y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]

[[0 4 0]
 [0 0 6]
 [5 0 0]]


array([[5, 3, 4],
       [6, 4, 5],
       [7, 5, 6]])

**Exercise 2**: Take a 10x2 matrix representing $(x1,x2)$ coordinates and transform them into polar coordinates $(r,\theta)$.

*Hint 1: the inverse transformation is given by $x1 = r\cos\theta$, $x2 = r\sin\theta$*

*Hint 2: generate random numbers with the functions in numpy.random*

In [34]:
z = np.random.random((10, 2))
x1, x2 = z[:, 0], z[:, 1]
R = np.sqrt(x1 ** 2 + x2 ** 2)
T = np.arctan2(x2, x1)
print(R)
print(T)

[ 0.94940813  1.16592904  0.60198319  0.48156392  0.73034869  0.71599528
  1.26160146  1.39674516  0.8470871   1.03554488]
[ 1.25433767  0.72775302  1.55247522  1.56007829  0.53933135  0.09109339
  0.83854253  0.78131988  0.94250228  1.15221789]


#### Transposing

Transposition is a very important operation for linear algebra. Although NumPy is capable of correctly doing matrix-vector products correctly regardless of the orientation of the vector, it is not the case for products of matrices

In [35]:
Z = np.arange(0, 12, 1).reshape((4, 3))

In [36]:
np.dot(Z, y)

array([ 17,  62, 107, 152])

In [37]:
np.dot(Z, y.T)

array([ 17,  62, 107, 152])

In [38]:
Z.dot(X)

array([[ 14,  17,  20],
       [ 50,  62,  74],
       [ 86, 107, 128],
       [122, 152, 182]])

In [39]:
(Z.T).dot(X)

ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

#### Array Methods

To not have to go from NumPy arrays to lists back and forth, NumPy contains some functions to know properties of your arrays. Actually, there are more of these functions than in standard Python.

In [40]:
a = np.array([-4, -2, 1, 3, 5])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

5
-4
3
0.6
3.26190128606


Some interesting functions are `argmax` and `argmin`, which return the index of the maximum and minimum values in the array.

In [41]:
print(a.argmax())
print(a.argmin())

4
0


### Indexing/Slicing

We have already seen briefly that to access individual elements you use the bracket notation: `array[ax_0, ax_1, ...]`, where the `ax_i` denotes the coordinate in the `i`-th axis. You can even use this to assign new values to your elements.

In [42]:
r = [4, 5, 6, 7]
print(r[2])
r[0] = 198
r

6


[198, 5, 6, 7]

To select a range of rows or columns you can use a colon :. A second : can be used to indicate the step size. `array[start:stop:stepsize]`. If you leave `start` (`stop`) blank, the selection will go from the very beginning (until the very end) of the array

In [43]:
s = np.arange(13)**2
print(s)
print(s[3:9])
print(s[2:10:3])
s[-5::-2]

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[ 9 16 25 36 49 64]
[ 4 25 64]


array([64, 36, 16,  4,  0])

The same applies to matrices or higher-dimensional arrays

In [44]:
r = np.arange(36).reshape((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [45]:
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

You can also select specific rows and columns, separated by commas

In [46]:
r[[1, 3, 4], 1:3]

array([[ 7,  8],
       [19, 20],
       [25, 26]])

A very useful tool is *conditional indexing*, where we apply a function, assignment... only to those elements of an array that satisfy some condition

In [47]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Exercise 3**: Create a random 1-dimensional array, and find which element is closest to 0.7

In [48]:
Z = np.random.uniform(0,1,100)
z = 0.7
m = Z[np.abs(Z - z).argmin()]
print(m)

0.690143367052


#### Copying Data

**Be very careful with copying and modifying arrays in NumPy!** You will see the reason right now. Let's begin defining `r2` as a slice of r

In [49]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

And now let's set all its elements to zero

In [50]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

When looking at `r`, we see that it has also been changed!

In [51]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

The proper way of handling selections without modifying the original arrays is through the `copy` command.

In [52]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now we can safely modify `r_copy` without affecting `r`.

In [53]:
r_copy[:] = 10
print('{}\n'.format(r_copy))
r

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]



array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Iterating Over Arrays

Finally, you can iterate over arrays in the same way as you iterate over lists

In [54]:
test = np.random.randint(0, 10, (4,3))
test

array([[2, 5, 2],
       [1, 9, 6],
       [6, 9, 4],
       [2, 2, 1]])

You can iterate by row:

In [55]:
for row in test:
    print(row)

[2 5 2]
[1 9 6]
[6 9 4]
[2 2 1]


Or by row index

In [56]:
for i in range(len(test)):
    print(test[i])

[2 5 2]
[1 9 6]
[6 9 4]
[2 2 1]


Or by row and index:

In [57]:
for i, row in enumerate(test):
    print('Row {} is {}'.format(i, row))

Row 0 is [2 5 2]
Row 1 is [1 9 6]
Row 2 is [6 9 4]
Row 3 is [2 2 1]


In the same way as with lists, you can use `zip` to iterate over multiple iterables.

In [58]:
test2 = test**2
test2

array([[ 4, 25,  4],
       [ 1, 81, 36],
       [36, 81, 16],
       [ 4,  4,  1]])

In [59]:
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[2 5 2] + [ 4 25  4] = [ 6 30  6]
[1 9 6] + [ 1 81 36] = [ 2 90 42]
[6 9 4] + [36 81 16] = [42 90 20]
[2 2 1] + [4 4 1] = [6 6 2]


**Exercise 4**: Create a function that iterates over the columns of a 2-dimensional array

In [63]:
def iterate(df):
    for i, row in enumerate(df):
        shp = row.shape
        row.shape = shp + (1,)
        print('Column {} is {}'.format(i, row))

iterate(test.T)

Column 0 is [[2]
 [1]
 [6]
 [2]]
Column 1 is [[5]
 [9]
 [9]
 [2]]
Column 2 is [[2]
 [6]
 [4]
 [1]]


### Loading and Saving Data

To load and save data NumPy has the `loadtxt` and `savetxt` commands. However, they only work for two-dimensional arrays

In [64]:
np.savetxt('numpytest.txt', test)
np.loadtxt('numpytest.txt')

array([[ 2.,  5.,  2.],
       [ 1.,  9.,  6.],
       [ 6.,  9.,  4.],
       [ 2.,  2.,  1.]])

## Pandas

When dealing with numeric matrices and vectors in Python, NumPy makes life a lot easier. For more complex data, however, it leaves a bit to be desired. For those used to working with dedicated languages like R, doing data analysis directly with numpy feels like a step back. Fortunately, some nice folks have written the Python Data Analysis Library (a.k.a. [pandas](http://pandas.pydata.org/)). Pandas provides an R-like DataFrame, produces high quality plots with matplotlib, and integrates nicely with other libraries that expect NumPy arrays.

Pandas works with `Series` of data, that then are arranged in `DataFrame`s. A dataframe will be the object closest to an Excel spreadsheet that you will see throughout the course (but of course, given that it is integrated in Python and can be combined with so many different packages, dataframes are much more powerful than Excel spreadsheets). The data in the series can be either qualitative or quantitative data. Creating a series is as easy as creating a NumPy array from a one-dimensional list.

In [65]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [66]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

Notice that the series is indexed by default by integers. You can change this indexing by using a dictionary instead of a list for creating the series.

In [67]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

On the other hand, `DataFrame`s can be built from two-dimensional arrays, with the ability of labelling columns and indexing the rows

In [68]:
u = pd.DataFrame(np.random.randn(1000,6), index=np.arange(0, 3000, 3), columns=['A', 'B', 'C', 'D', 'E', 'F'])
u

A         B         C         D         E         F
0    -0.734159  1.394964  0.190682  1.498369 -0.210405 -1.361742
3    -0.662306  0.630799  1.232813 -0.426428  1.097235 -1.397559
6     0.439180 -0.914989 -1.835617  0.646149  1.238249  0.170807
9    -0.672628  0.126726  0.090665  0.716471  0.007468  0.636851
12    0.269581  0.097735 -0.186836 -0.865343  0.161044 -1.075828
15   -0.512721 -0.764128 -0.206305  0.090615 -1.810880  0.630148
18   -1.231736 -0.518864  0.037573 -0.060409 -1.349120 -0.099815
21   -1.131978  0.388589  1.438963 -0.270093  0.827176  0.990323
24    0.802202  0.106492  0.217208 -2.603605  0.448975  0.179115
27   -0.758796 -0.475212  0.138164 -1.317393 -0.068242  0.992660
30   -1.337185 -0.318061 -0.369541 -1.059426 -1.272904 -0.430286
33    1.099143 -1.137359  1.638740 -1.302597  0.670333  0.286842
36   -0.202148  2.177661 -1.756213 -2.215062  0.886999  1.516695
39    0.872205 -1.365958 -1.448306 -1.906542 -0.758620 -0.891438
42   -0.152168 -0.506718  0.161787  1.421858 -0.448334 -0.520599
45   -0.145302  0.801955 -0.125383  1.114851 -1.296043 -0.181965
48    0.177844 -1.905952  0.555964 -0.249770  0.719770  0.253243
51    1.229710  0.308772 -0.582096  1.302642  0.461758 -1.293553
54   -0.159183 -0.333924 -1.511544 -0.186878  0.310935 -1.123667
57    0.597304 -1.568620  1.355420 -0.307611  0.199345  0.293836
60   -1.464668 -0.014770  0.843016  1.176948  0.328041 -0.491906
63   -1.652767 -0.513009  0.375169  1.268120 -0.392922  0.515360
66    2.561961  1.723727  0.332625 -0.412011  0.617972 -1.315629
69   -0.257666  0.390738  0.900184  0.027890  1.110999 -1.383279
72   -0.210115  0.015682 -0.273660  0.710361  0.478134  0.416070
75    1.850700  0.722518 -1.450022  3.471712  1.411073  0.664941
78   -0.189542 -0.518810 -0.613843  1.452510  0.161746 -0.157046
81    1.188583 -0.042670 -1.318416 -0.497786  1.469176 -2.274682
84   -1.157549 -1.477121 -0.174957  0.187075 -0.514212  1.201097
87    0.297707 -0.681167 -0.633112 -0.629691 -0.470936 -1.105767
...        ...       ...       ...       ...       ...       ...
2910  0.441837 -2.858965  0.074106  0.086447 -0.987088 -0.292977
2913 -1.081924  0.107186  0.426375  0.872325 -0.567102 -1.073130
2916  2.050551  0.908870 -0.431704  1.744821 -0.035908  0.078235
2919 -0.488238 -1.116222  0.267685 -0.477515  0.955435  0.040388
2922 -0.011368 -0.702594  0.452328  1.772061 -0.985164  0.907382
2925 -0.727745  0.735233  1.112844  1.324979  0.577337 -1.227353
2928 -1.287337  0.864253 -0.141967  1.229645 -0.595956 -0.329679
2931 -2.196506  0.373295  1.383618  0.084307  0.070877  1.936662
2934 -0.635401 -1.556345  0.488439  0.089933  0.373741  1.151044
2937 -0.428014 -0.821007  0.805775 -1.541945  1.584413 -0.992480
2940  2.356060 -0.223255  0.151434  1.148847 -1.957645  2.636493
2943  0.764799  0.684897  0.208729 -2.089727  0.112400  0.686830
2946  0.366970 -0.710280  0.567466  0.716803  0.518111 -0.380624
2949 -1.150128  0.398146 -1.577798  1.119661  0.271756 -0.744547
2952  0.478940  0.357920 -0.514510 -1.240471 -0.926650 -0.969323
2955 -0.034377 -0.741881 -0.796524  0.145587  0.901385 -0.972359
2958 -0.841932 -0.159310  1.614985  0.200896 -1.112758  0.285245
2961 -2.539036 -0.951688  0.221083 -2.060121  0.055321  0.471608
2964  0.489410  0.466041 -1.934208 -0.734892 -0.635348  0.982536
2967  1.934711 -1.751339  1.271481  0.442069 -0.479983  0.683042
2970 -1.238175  1.374612 -1.582618 -0.434171  0.045697 -0.567534
2973 -1.469821 -1.008030 -0.003018  0.678080  0.395680  1.130750
2976 -0.731545 -0.832930  0.056563  2.230471 -1.974263 -1.520708
2979 -1.533043 -0.182422 -0.661062 -0.053276 -0.482565 -1.278152
2982  1.451983  0.930824  0.996970 -0.192904 -0.070283 -1.543573
2985 -0.427060 -1.660207  0.736184 -0.299801  0.395256  1.199968
2988  0.457466  0.553464  1.568200  0.462077 -0.939801  0.516738
2991  0.097238 -0.121657 -0.130031  0.272273 -1.110792 -0.658494
2994 -0.102260  0.278222 -0.722962 -0.342476  2.216141  0.785061
2997 -1.655279  1.141087  0.669389  1.216415 -0.

As you might have noticed, it is a bit ugly to deal with large dataframes. There are however some functions that allows to have an idea of the data in a frame.

In [69]:
u.head()

A         B         C         D         E         F
0  -0.734159  1.394964  0.190682  1.498369 -0.210405 -1.361742
3  -0.662306  0.630799  1.232813 -0.426428  1.097235 -1.397559
6   0.439180 -0.914989 -1.835617  0.646149  1.238249  0.170807
9  -0.672628  0.126726  0.090665  0.716471  0.007468  0.636851
12  0.269581  0.097735 -0.186836 -0.865343  0.161044 -1.075828

In [70]:
u.tail()

A         B         C         D         E         F
2985 -0.427060 -1.660207  0.736184 -0.299801  0.395256  1.199968
2988  0.457466  0.553464  1.568200  0.462077 -0.939801  0.516738
2991  0.097238 -0.121657 -0.130031  0.272273 -1.110792 -0.658494
2994 -0.102260  0.278222 -0.722962 -0.342476  2.216141  0.785061
2997 -1.655279  1.141087  0.669389  1.216415 -0.113118  0.642230

In [71]:
u.describe()

A            B            C            D            E  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     -0.027445    -0.017884     0.041646    -0.019619     0.029266   
std       0.992676     0.990085     0.981469     0.990599     1.036345   
min      -3.721742    -3.130139    -2.918708    -3.451850    -3.082377   
25%      -0.674439    -0.719319    -0.666068    -0.663017    -0.670601   
50%      -0.035951    -0.027702     0.050864    -0.041865     0.048758   
75%       0.654368     0.626682     0.682900     0.642272     0.762600   
max       3.040135     3.339068     4.517622     3.689939     3.029372   

                 F  
count  1000.000000  
mean      0.039012  
std       0.996237  
min      -3.266857  
25%      -0.668938  
50%       0.085713  
75%       0.706860  
max       3.136949

### Indexing/Slicing in Pandas

The easiest way of accessing information in a Pandas dataframe, equivalent to the way used in NumPy, is using the `iloc` command. With this you can also set specific values, do conditional indexing... all that we have seen before in section 2.4

In [72]:
u.iloc[125:132,[0, 2, 5]]

A         C         F
375  0.336485  0.210328  1.907802
378 -0.990793  0.638109  1.265564
381  0.221572  0.146957 -0.659925
384  1.110908 -1.060390  0.343383
387  0.929190 -0.377071 -0.218922
390  1.483071 -1.136177 -0.347253
393  0.727969  0.813934  1.207470

However, there are a few different ways of accessing the data in a Pandas dataframe, that typically have a more "direct" connection with the actual content fo the dataframe. Individual or sets of columns can also be accessed by their column names. Choosing one single column will give a Series, while two or more will produce a Dataset

In [73]:
u['A'].head()

0    -0.734159
3    -0.662306
6     0.439180
9    -0.672628
12    0.269581
Name: A, dtype: float64

In [74]:
u[['A', 'D']].head()

A         D
0  -0.734159  1.498369
3  -0.662306 -0.426428
6   0.439180  0.646149
9  -0.672628  0.716471
12  0.269581 -0.865343

Not only that, you can access a single column without the need of brackets []

In [75]:
u.A.head()

0    -0.734159
3    -0.662306
6     0.439180
9    -0.672628
12    0.269581
Name: A, dtype: float64

The usual [] will select specific rows according to the row number

In [76]:
u[0:10][list('BCF')]

B         C         F
0   1.394964  0.190682 -1.361742
3   0.630799  1.232813 -1.397559
6  -0.914989 -1.835617  0.170807
9   0.126726  0.090665  0.636851
12  0.097735 -0.186836 -1.075828
15 -0.764128 -0.206305  0.630148
18 -0.518864  0.037573 -0.099815
21  0.388589  1.438963  0.990323
24  0.106492  0.217208  0.179115
27 -0.475212  0.138164  0.992660

You can also choose specific rows according to their indices with the `loc` command

In [77]:
u.loc[6:15]

A         B         C         D         E         F
6   0.439180 -0.914989 -1.835617  0.646149  1.238249  0.170807
9  -0.672628  0.126726  0.090665  0.716471  0.007468  0.636851
12  0.269581  0.097735 -0.186836 -0.865343  0.161044 -1.075828
15 -0.512721 -0.764128 -0.206305  0.090615 -1.810880  0.630148

Or, you can access just the elements that satisfy some condition

In [78]:
u[u.D > 2]

A         B         C         D         E         F
75    1.850700  0.722518 -1.450022  3.471712  1.411073  0.664941
387   0.929190 -1.940692 -0.377071  2.370498 -0.676712 -0.218922
429  -1.414435 -0.194824  0.821353  2.067461 -0.639616  0.824829
561   1.661663 -0.719469 -0.515072  2.640557 -0.287310  0.987437
750  -0.629037 -0.567375 -1.502560  2.469552  0.837578 -0.017394
1269  0.474302 -0.291709  0.681740  2.182586  1.299562 -0.137582
1323  0.247099 -0.331393 -0.057057  2.443179  0.042872  0.998506
1365  1.319477  0.226238 -0.235746  2.218785  0.172797 -0.333913
1449 -0.380635  1.216693  0.241914  2.271371 -1.391959 -0.656318
1710  0.300307 -0.007317 -1.018120  2.307998  0.796519  0.197903
1806  0.907802  0.367178  0.159605  2.199405 -1.912372  0.938928
1965  0.384646 -0.832416  0.631709  2.314562  1.636637  1.144389
2214  1.284728 -1.665398 -1.250583  2.222073  1.165096 -2.113329
2235  1.193591  0.974218  0.150168  3.689939 -1.954431 -0.092275
2250  1.351875  0.552024  0.285975  2.507065 -0.101366  0.996261
2334 -0.206749  0.656069  0.803320  2.087650  1.305849  1.122543
2436 -0.613631 -1.526000  0.334225  2.095945  0.813100 -0.703555
2628 -1.058415 -0.325328 -0.538026  2.360591  0.240599  0.182129
2727 -0.602928 -1.360152  0.460694  2.545261 -1.396709 -0.711038
2745 -0.383983  0.498755  1.379903  2.668076 -1.167219 -0.868843
2844  0.015743  1.342738 -1.004988  2.332355 -0.413424 -1.743455
2880  3.029741  0.503321 -0.168036  2.499740 -0.466593 -1.435931
2976 -0.731545 -0.832930  0.056563  2.230471 -1.974263 -1.520708

### Applying Functions

An interesting capability of Pandas is that you can apply functions to the whole dataset or specific columns with the `apply` command

In [79]:
def func(x):
    return 1 / x

u['F'] = u['F'].apply(func)
u['F'].head()

0    -0.734353
3    -0.715533
6     5.854544
9     1.570225
12   -0.929517
Name: F, dtype: float64

`apply` acts on the whole column at a time, so you can compute things that depend on several values of the column, for instance the mean value. To apply functions in a real element-by-element basis the function `applymap` should be used.

In [80]:
def mn(col):
    return sum(col) / len(col)

u.apply(mn)

A   -0.027445
B   -0.017884
C    0.041646
D   -0.019619
E    0.029266
F    3.415105
dtype: float64

Functions can also be applied to columns with strings or categorical data. The limit is the imagination.


### Combining `DataFrames`

Something we will do quite often as scientists is combining data from different sources into one single source. This can be achieved by different commands in Pandas, depending on the actual goal we want.

To begin with, appending new rows of data is achieved by the command `append`.

In [81]:
newdata = pd.DataFrame(np.ones((5, 6)), index=np.arange(3003, 3018, 3), columns=list('ABCDEF'))
newdata

A    B    C    D    E    F
3003  1.0  1.0  1.0  1.0  1.0  1.0
3006  1.0  1.0  1.0  1.0  1.0  1.0
3009  1.0  1.0  1.0  1.0  1.0  1.0
3012  1.0  1.0  1.0  1.0  1.0  1.0
3015  1.0  1.0  1.0  1.0  1.0  1.0

In [82]:
unew = u.append(newdata)
unew.tail(10)

A         B         C         D         E         F
2985 -0.427060 -1.660207  0.736184 -0.299801  0.395256  0.833356
2988  0.457466  0.553464  1.568200  0.462077 -0.939801  1.935216
2991  0.097238 -0.121657 -0.130031  0.272273 -1.110792 -1.518617
2994 -0.102260  0.278222 -0.722962 -0.342476  2.216141  1.273786
2997 -1.655279  1.141087  0.669389  1.216415 -0.113118  1.557075
3003  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

The same result can be obtained with `concat`.

In [83]:
pd.concat([u, newdata]).tail(10)

A         B         C         D         E         F
2985 -0.427060 -1.660207  0.736184 -0.299801  0.395256  0.833356
2988  0.457466  0.553464  1.568200  0.462077 -0.939801  1.935216
2991  0.097238 -0.121657 -0.130031  0.272273 -1.110792 -1.518617
2994 -0.102260  0.278222 -0.722962 -0.342476  2.216141  1.273786
2997 -1.655279  1.141087  0.669389  1.216415 -0.113118  1.557075
3003  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

Appending new columns of data can be achieved with the command `join`.

In [84]:
newcol = pd.Series(np.ones(1000,), name='G')
u.join(newcol).head()

A         B         C         D         E         F    G
0  -0.734159  1.394964  0.190682  1.498369 -0.210405 -0.734353  1.0
3  -0.662306  0.630799  1.232813 -0.426428  1.097235 -0.715533  1.0
6   0.439180 -0.914989 -1.835617  0.646149  1.238249  5.854544  1.0
9  -0.672628  0.126726  0.090665  0.716471  0.007468  1.570225  1.0
12  0.269581  0.097735 -0.186836 -0.865343  0.161044 -0.929517  1.0

### Loading and saving dataframes

To load and save Pandas dataframes we will use the `to_csv` and `read_csv` commands

In [85]:
u.to_csv('test.csv')
v = pd.read_csv('test.csv', index_col=0)
v.head()

A         B         C         D         E         F
0  -0.734159  1.394964  0.190682  1.498369 -0.210405 -0.734353
3  -0.662306  0.630799  1.232813 -0.426428  1.097235 -0.715533
6   0.439180 -0.914989 -1.835617  0.646149  1.238249  5.854544
9  -0.672628  0.126726  0.090665  0.716471  0.007468  1.570225
12  0.269581  0.097735 -0.186836 -0.865343  0.161044 -0.929517

But, as an addition, Pandas has special commands to load and save Excel spreadsheets (yay!). However, to use it you'll need the `openpyxl` and `xlrd` packages.

In [86]:
u.to_excel('test.xlsx', sheet_name='My sheet')
pd.read_excel('test.xlsx', 'My sheet', index_col=0).head()

A         B         C         D         E         F
0  -0.734159  1.394964  0.190682  1.498369 -0.210405 -0.734353
3  -0.662306  0.630799  1.232813 -0.426428  1.097235 -0.715533
6   0.439180 -0.914989 -1.835617  0.646149  1.238249  5.854544
9  -0.672628  0.126726  0.090665  0.716471  0.007468  1.570225
12  0.269581  0.097735 -0.186836 -0.865343  0.161044 -0.929517

**Exercise 5**: Download [this dataset](https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv) and load it, using the first column as the index. Take a look at it, and do the following things:
- Choose the columns 'Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1' and 'Type2' 
- Create a function that lowercases strings and apply it to 'Type1' and 'Type2' (*Extra: just capitalize the strings, i.e., leave the first letter uppercase and lowercase the rest*)
- Create a function that returns a Boolean value (don't be afraif by this, it is a function that returns either True or False) that tells if a Pokémon has high stamina (BaseStamina>170) or not. Store this information in a new column and show the list of Pokémon with high stamina
- Show the instructor the last 15 rows of your dataset

In [87]:
df = pd.read_csv('https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv', index_col=0)

df = df[['Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1', 'Type2']]

capitalize = lambda st: st.capitalize()

for col in ['Type1', 'Type2']:
    df[col] = df[col].apply(capitalize)
    
def highstamina(x):
    return True if x > 170 else False

df['HighStamina'] = df.BaseStamina.apply(highstamina)

print(df[df['HighStamina'] == True].Identifier)

df.tail(15)

PkMn
31      Nidoqueen
36       Clefable
39     Jigglypuff
40     Wigglytuff
59       Arcanine
62      Poliwrath
68        Machamp
79       Slowpoke
80        Slowbro
87        Dewgong
89            Muk
103     Exeggutor
108     Lickitung
112        Rhydon
113       Chansey
115    Kangaskhan
130      Gyarados
131        Lapras
134      Vaporeon
143       Snorlax
144      Articuno
145        Zapdos
146       Moltres
149     Dragonite
150        Mewtwo
151           Mew
Name: Identifier, dtype: object


Identifier  BaseStamina  BaseAttack  BaseDefense     Type1   Type2  \
PkMn                                                                       
137      Porygon          130         156          158    Normal    None   
138      Omanyte           70         132          160      Rock   Water   
139      Omastar          140         180          202      Rock   Water   
140       Kabuto           60         148          142      Rock   Water   
141     Kabutops          120         190          190      Rock   Water   
142   Aerodactyl          160         182          162      Rock  Flying   
143      Snorlax          320         180          180    Normal    None   
144     Articuno          180         198          242       Ice  Flying   
145       Zapdos          180         232          194  Electric  Flying   
146      Moltres          180         242          194      Fire  Flying   
147      Dratini           82         128          110    Dragon    None   
148    Dragonair          122         170          152    Dragon    None   
149    Dragonite          182         250          212    Dragon  Flying   
150       Mewtwo          212         284          202   Psychic    None   
151          Mew          200         220          220   Psychic    None   

      HighStamina  
PkMn               
137         False  
138         False  
139         False  
140         False  
141         False  
142         False  
143          True  
144          True  
145          True  
146          True  
147         False  
148         False  
149          True  
150          True  
151          True