# 4 NumPy and Pandas

## Introduction

After getting used to how Python works, it is the moment to begin getting our hands dirty with data analysis. We will study two packages: [NumPy](http://www.numpy.org/) is the fundamental numeric computing and linear algebra package in Python, that allows for decent data analysis. We will learn it not only for the data analysis, but more importantly because it will be a package that will be always present in our `import` section as scientists. After NumPy we will go to [Pandas](http://pandas.pydata.org/). Pandas is a dedicated data analysis package with a lot more functionalities than NumPy, making our life much easier in terms of data visualization and manipulation. All the power of Pandas will be completely unleashed in Section 5, where we will see how to visualize information in plots.

As usual, we begin importing the necessary packages

In [1]:
import numpy as np
print('NumPy:', np.__version__)

NumPy: 1.21.0


## Numeric Python (NumPy)

NumPy is an open-source add-on module to Python that provides common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that
associated with common commercial software like MATLAB. The [NumPy](http://www.numpy.org/) (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. The main object NumPy works with is a *homogeneous multidimensional array*. Despite its intimidating name, these are nothing but tables of numbers, each labelled by a tuple of indices.

We will now explore some capabilities of NumPy that will prove very useful not only for data analyisis, but throughout all our life with Python.

### Creating Arrays

As mentioned before, the main object in NumPy is the *array*. Creating one is as easy as calling the command `array`

In [2]:
# Create a list
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Create a numpy array from a list
my1darr = np.array(mylist)

# Data type of a numpy array
print(type(my1darr))

my1darr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

The same applies to multidimensional arrays

In [3]:
# Create a numpy array with three elemets, with three elements each.
my2darr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my2darr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Create a numpy array with three elemets, with three elements each, with a single element each
my3darr = np.array([  [ [1], [2], [3] ], [ [4], [5], [6] ], [ [7], [8], [9] ]  ])
my3darr

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

A NumPy array has a number of dimensions (or *axes*). To obtain the number of axes and the size of each of them you use the command `shape`. For 2-dimensional arrays (matrices), the order corresponds to (rows, columns)

There are two different ways of calling the `shape` command, either with `np.shape(arr)` or `arr.shape`. This is not the only command that works in both formats, and we will be finding some more in our way.

In [5]:
# Shape using `.shape`
print(my1darr.shape)
print(my2darr.shape)
print(my3darr.shape)

# Shape using `np.shape()`
print(np.shape(my1darr))
print(np.shape(my2darr))
print(np.shape(my3darr))

(9,)
(3, 3)
(3, 3, 1)
(9,)
(3, 3)
(3, 3, 1)


There is one restriction with respect to the use of lists: while you could create lists with data of different type, all the data in an array has to be of the same type, and it will be converted automatically.

In [6]:
# Create a list with floats and strings
lst = [1., 'cat']
print((lst[0]))

# Create a numpy array from a list with mixed data types
arr = np.array(lst)
print((arr[0]))

# The data type of the 1. in the list is the same data type than the 1. in the array?
print( type((lst[0])) == type((arr[0])) )
print(type(lst[0]))
print(type(arr[0]))

1.0
1.0
False
<class 'float'>
<class 'numpy.str_'>


(We will go deeper into indexing in a while)

### Special Arrays

Now we review some built-in functions that create matrices commonly used. `ones` and `zeros` return arrays of given shape and type (default is float64), filled with ones or zeros, respectively.

In [7]:
# Create a zero-filled numpy array of shape 3 x 2
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
# Create a one-filled numpy array of shape 3 x 2 x 4
np.ones((3, 2, 4), dtype=np.int8)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

`eye(d)` returns a 2-D, dimension-$d$ array with ones on the diagonal and zeros elsewhere.

In [9]:
# Create an numpy array of shape 3 x 3 with ones in the diagonal
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`eye` can also create arrays with ones in upper and lower diagonals. To achieve this, you must call `eye(d, d, k)` where $k$ denotes the diagonal (positive for above the center diagonal, negative for below), or `eye(d, k=num)`

In [10]:
# Create an numpy array of shape 5 x 5 with ones in the diagonal shifted-up 2 positions
print(np.eye(5, 5, 2))
print('\n')

# Create an numpy array of shape 4 x 4 with ones in the diagonal shifted-down 1 position
print(np.eye(4, k=-1))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


`diag`, depending on the input, either constructs a diagonal array (if the input is a 1-D array) or extracts a diagonal from a matrix (if the input is a 2-D array).

In [11]:
# Create a 2-D array with the array `my1darr` shifted-up 1 position with respect the diagonal 
np.diag(my1darr, 1)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
# The the diagonal from the 2-D array `my2darr`
np.diag(my2darr)

array([1, 5, 9])

In [13]:
# Create a 2-D array with the diagonal from the 2-D array `my2darr` shifted-down 1 position with respect the diagonal 
np.diag(np.diag(my2darr), -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 9, 0]])

`arange(begin, end, step)` returns evenly spaced values within a given interval. Note that the beginning point is included, but not the ending.

In [14]:
# Create range with start at 0, stop before 16, counting up by 2
myrange = np.arange(0, 16, 2)
myrange

array([ 0,  2,  4,  6,  8, 10, 12, 14])

**Exercise 1**: Create an array of the first million of odd numbers, both with `arange` and using loops. Try timing both methods to see which one is faster. For that, use `%timeit`.

In [15]:
%timeit np.arange(0, 2000000, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

1.2 ms ± 26.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
134 ms ± 1.99 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Similarly, `linspace(begin, end, points)` returns evenly spaced numbers over a specified interval. Here, instead of specifying the step, you specify the amount of points you want. Also with `linspace` you include the ending of the interval.

In [16]:
# Create line with start at 0, stop at 14, getting 7 evenly spaced points
myline = np.linspace(0, 14, 8) # 
myline

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [17]:
# Print the length of `myrange` and `myline`
print(len(myrange))
print(len(myline))

8
8


`reshape` changes the shape of an array, but not its data. This is another of the commands that can be called before or after the array.

In [18]:
# Reshape `myrange` using `np.reshape()`
print(np.reshape(myrange, (2, 4)))
print(np.reshape(myrange, (4, 2)))

print('\n')

# Reshape `myrange` using `.reshape()`
print(myrange.reshape(2, 4))
print(myrange.reshape(4, 2))

[[ 0  2  4  6]
 [ 8 10 12 14]]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


[[ 0  2  4  6]
 [ 8 10 12 14]]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


Note however that, in order for these changes to be permanent, you should do a reassignment of the variable

In [19]:
# After the reshapings above, the original array stays being the same
myrange  

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [20]:
mynewrange = myrange.reshape(2, 4)
# Now that we have reassigned it is when it definitely changes shape
mynewrange  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

### Combining Arrays

The most general command for combining arrays is `concatenate(arrs, d)`. It takes a list of arrays and concatenates them along axis $d$. Remember your 3-D array:

In [21]:
# Remember the `my3darr` 3-D numpy array
print(my3darr)
print(my3darr.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [22]:
# Concatenate `my3darr` with itsef multiplied by 10 along dimension 0
conc_along0 = np.concatenate([my3darr, 10 * my3darr], 0)
print(conc_along0)
print(conc_along0.shape)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [20]
  [30]]

 [[40]
  [50]
  [60]]

 [[70]
  [80]
  [90]]]
(6, 3, 1)


In [23]:
# Concatenate `my3darr` with itsef multiplied by 10 along dimension 1
conc_along1 = np.concatenate([my3darr, 10 * my3darr], 1)
print(conc_along1)
print(conc_along1.shape)

[[[ 1]
  [ 2]
  [ 3]
  [10]
  [20]
  [30]]

 [[ 4]
  [ 5]
  [ 6]
  [40]
  [50]
  [60]]

 [[ 7]
  [ 8]
  [ 9]
  [70]
  [80]
  [90]]]
(3, 6, 1)


In [24]:
# Concatenate `my3darr` with itsef multiplied by 10 along dimension 2
conc_along2 = np.concatenate([my3darr, 10 * my3darr], 2)
print(conc_along2)
print(conc_along2.shape)

[[[ 1 10]
  [ 2 20]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]

 [[ 7 70]
  [ 8 80]
  [ 9 90]]]
(3, 3, 2)


However, for common combinations there exist special commands. Use `vstack` to stack arrays in sequence vertically (row wise), `hstack` to stack arrays in sequence horizontally (column wise).

In [25]:
# Remember the `my1darr` 1-D numpy array from above
print(my1darr)
print(my1darr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [26]:
# Stack `my1darr` vertically and horizontally
print(np.vstack([my1darr, 10 * my1darr]))
print('\n')
print(np.hstack([my1darr, 10 * my1darr]))

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]


[ 1  2  3  4  5  6  7  8  9 10 20 30 40 50 60 70 80 90]


In [27]:
# Remember the `my2darr` 2-D numpy array from above
print(my2darr)
print(my2darr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [28]:
# Stack `my2darr` vertically and horizontally
print(np.vstack([my2darr, 10 * my2darr]))
print('\n')
print(np.hstack([my2darr, 10 * my2darr]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]


### Operations

You can perform easily element-wise operations on arrays of any shape. Use the typical symbols, +, -, \*, / and \*\* to perform element-wise addition, subtraction, multiplication, division and power.

In [29]:
x = np.array([1, 2, 3])
print(x)
print(x + 10)
print(3 * x)
print(1 / x)
print(x ** (-2 / 3))
print(2 ** x)

[1 2 3]
[11 12 13]
[3 6 9]
[1.         0.5        0.33333333]
[1.         0.62996052 0.48074986]
[2 4 8]


Also (and obviously) these symbols can be used to operate between two arrays, which must be of the same shape. If this is the case, they also do element-wise operations

In [30]:
y = np.arange(4, 7, 1)
print(x + y)     # [1+4, 2+5, 3+6]
print(x * y)     # [1*4, 2*5, 3*6]
print(x / y)     # [1/4, 2/5, 3/6]
print(x ** y)    # [1**4, 2**5, 3**6]

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


For doing vector or matrix multiplication, the command to be used is `dot`

In [31]:
print(x)
print(y)
x.dot(y)  # 1*4 + 2*5 + 3*6

[1 2 3]
[4 5 6]


32

With python 3.5 matrix multiplication got it's own operator

In [32]:
print(x)
print(y)
x @ y  # 1*4 + 2*5 + 3*6

[1 2 3]
[4 5 6]


32

In [33]:
X = np.array([[i + j for i in range(3, 6)] for j in range(3)])
Y = np.diag([1, 1], 1) + np.diag([1], -2)

print(X)
print('\n')
print(Y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]


[[0 1 0]
 [0 0 1]
 [1 0 0]]


The operator `*` returns the elements-wise multiplication of arrays with the same shape.

In [34]:
X * Y

array([[0, 4, 0],
       [0, 0, 6],
       [5, 0, 0]])

The operator `@` returns the product of arrays compatible shapes.

In [35]:
X @ Y

array([[5, 3, 4],
       [6, 4, 5],
       [7, 5, 6]])

**Exercise 2**: Take a 10x2 matrix representing $(x1,x2)$ coordinates and transform them into polar coordinates $(r,\theta)$.

*Hint 1: the inverse transformation is given by $x1 = r\cos\theta$, $x2 = r\sin\theta$*

*Hint 2: generate random numbers with the functions in numpy.random*

In [36]:
z = np.random.random((10, 2))
x1, x2 = z[:, 0], z[:, 1]
R = np.sqrt(x1 ** 2 + x2 ** 2)
T = np.arctan2(x2, x1)
print(R)
print(T)

[0.36320643 0.7211909  1.1128058  0.47301587 1.11097976 0.73025988
 0.62726237 0.67379782 1.0605135  1.05922789]
[0.64442544 1.2100256  0.92120452 1.03554393 0.8748161  0.93187241
 1.4123739  1.23193151 1.04596646 0.43061869]


#### Transposing

Transposition is a very important operation for linear algebra. Although NumPy is capable of correctly doing matrix-vector products correctly regardless of the orientation of the vector, it is not the case for products of matrices

In [37]:
Z = np.arange(0, 12, 1).reshape((4, 3))

In [38]:
print(Z)
print(y)
Z @ y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4 5 6]


array([ 17,  62, 107, 152])

In [39]:
print(Z)
print(y.T)
Z @ y.T

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4 5 6]


array([ 17,  62, 107, 152])

In [40]:
print(Z)
print(X)
Z @ X  # (4 rows and 3 cols) @ (3 rows and 3 cols) yields (4 rows and 3 cols)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


array([[ 14,  17,  20],
       [ 50,  62,  74],
       [ 86, 107, 128],
       [122, 152, 182]])

In [41]:
print(Z.T)
print(X)
#Z.T @ X  # (3 rows and 4 cols) @ (3 rows and 3 cols) yields error

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


#### Array Methods

To not have to go from NumPy arrays to lists back and forth, NumPy contains some functions to know properties of your arrays. Actually, there are more of these functions than in standard Python.

In [42]:
a = np.array([-4, -2, 1, 3, 5])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

5
-4
3
0.6
3.2619012860600183


Some interesting functions are `argmax` and `argmin`, which return the index of the maximum and minimum values in the array.

In [43]:
print(a.argmax())
print(a.argmin())

4
0


### Indexing/Slicing

We have already seen briefly that to access individual elements you use the bracket notation: `array[ax_0, ax_1, ...]`, where the `ax_i` denotes the coordinate in the `i`-th axis. You can even use this to assign new values to your elements.

In [44]:
r = [4, 5, 6, 7]
print(r[2])
# Reassigning the value stored in index 0
r[0] = 198
r

6


[198, 5, 6, 7]

To select a range of rows or columns you can use a colon `:`. A second `:` can be used to indicate the step size. `array[start:stop:stepsize]`. If you leave `start` (`stop`) blank, the selection will go from the very beginning (until the very end) of the array

In [45]:
s = np.arange(13)**2
print(s)

# Starting by index 2, until index 10, pick each element
print(s[3:10])

# Starting by index 2, until index 10, pick every 3 elements 
print(s[2:10:3])

# Starting by index -5, until the end, pick every 2 elements
print(s[-5::2])

# Starting by index -5, until the end, pick every 2 elements backwards
print(s[-5::-2])

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[ 9 16 25 36 49 64 81]
[ 4 25 64]
[ 64 100 144]
[64 36 16  4  0]


The same applies to matrices or higher-dimensional arrays

In [46]:
r = np.arange(36).reshape((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
# Pick rows 2 to 5, and cols 1 to 3 (remember, row 5 and col 3 not included)
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

You can also select specific rows and columns, separated by commas

In [48]:
# Pick rows 1, 3 and 4, and cols 1 to 3 (remember, col 3 not included)
r[[1, 3, 4], 1:3]

array([[ 7,  8],
       [19, 20],
       [25, 26]])

A very useful tool is *conditional indexing*, where we apply a function, assignment... only to those elements of an array that satisfy some condition

In [49]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Exercise 3**: Create a random 1-dimensional array, and find which element is closest to 0.7

In [50]:
Z = np.random.uniform(0,1,100)
z = 0.7
m = Z[np.abs(Z - z).argmin()]
print(m)

0.6875432133749239


#### Copying Data

**Be very careful with copying and modifying arrays in NumPy!** You will see the reason right now. Let's begin defining `r2` as a slice of r

In [51]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

And now let's set all its elements to zero

In [52]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

When looking at `r`, we see that it has also been changed!

In [53]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

The proper way of handling selections without modifying the original arrays is through the `copy` command.

In [54]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now we can safely modify `r_copy` without affecting `r`.

In [55]:
r_copy[:] = 10
print('f{r_copy}\n')
r

f{r_copy}



array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Iterating Over Arrays

Finally, you can iterate over arrays in the same way as you iterate over lists

In [56]:
test = np.random.randint(0, 10, (4,3))
test

array([[0, 0, 7],
       [2, 8, 2],
       [2, 6, 6],
       [3, 6, 4]])

You can iterate by row:

In [57]:
for row in test:
    print(row)

[0 0 7]
[2 8 2]
[2 6 6]
[3 6 4]


Or by row index

In [58]:
for i in range(len(test)):
    print(test[i])

[0 0 7]
[2 8 2]
[2 6 6]
[3 6 4]


Or by row and index:

In [59]:
for i, row in enumerate(test):
    print(f'Row {i} is {row}')

Row 0 is [0 0 7]
Row 1 is [2 8 2]
Row 2 is [2 6 6]
Row 3 is [3 6 4]


In the same way as with lists, you can use `zip` to iterate over multiple iterables.

In [60]:
test2 = test**2
test2

array([[ 0,  0, 49],
       [ 4, 64,  4],
       [ 4, 36, 36],
       [ 9, 36, 16]], dtype=int32)

In [61]:
for i, j in zip(test, test2):
    print(f'{i} + {j} = {i+j}')

[0 0 7] + [ 0  0 49] = [ 0  0 56]
[2 8 2] + [ 4 64  4] = [ 6 72  6]
[2 6 6] + [ 4 36 36] = [ 6 42 42]
[3 6 4] + [ 9 36 16] = [12 42 20]


**Exercise 4**: Create a function that iterates over the columns of a 2-dimensional array

In [62]:
def iterate(df):
    for i, row in enumerate(df):
        shp = row.shape
        row.shape = shp + (1,)
        print(f'Column {i} is {row}')

iterate(test.T)

Column 0 is [[0]
 [2]
 [2]
 [3]]
Column 1 is [[0]
 [8]
 [6]
 [6]]
Column 2 is [[7]
 [2]
 [6]
 [4]]


### Loading and Saving Data

To load and save data NumPy has the `loadtxt` and `savetxt` commands. However, they only work for two-dimensional arrays

In [63]:
np.savetxt('numpytest.txt', test)
np.loadtxt('numpytest.txt')

array([[0., 0., 7.],
       [2., 8., 2.],
       [2., 6., 6.],
       [3., 6., 4.]])

## Pandas

When dealing with numeric matrices and vectors in Python, NumPy makes life a lot easier. For more complex data, however, it leaves a bit to be desired. For those used to working with dedicated languages like R, doing data analysis directly with numpy feels like a step back. Fortunately, some nice folks have written the Python Data Analysis Library (a.k.a. [pandas](http://pandas.pydata.org/)). Pandas provides an R-like DataFrame, produces high quality plots with matplotlib, and integrates nicely with other libraries that expect NumPy arrays.

Pandas works with `Series` of data, that then are arranged in `DataFrame`s. A dataframe will be the object closest to an Excel spreadsheet that you will see throughout the course (but of course, given that it is integrated in Python and can be combined with so many different packages, dataframes are much more powerful than Excel spreadsheets). The data in the series can be either qualitative or quantitative data. Creating a series is as easy as creating a NumPy array from a one-dimensional list.

In [64]:
import pandas as pd
print('Pandas:', pd.__version__)

Pandas: 1.3.1


In [65]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [66]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

Notice that the series is indexed by default by integers. You can change this indexing by using a dictionary instead of a list for creating the series.

In [67]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

On the other hand, `DataFrame`s can be built from two-dimensional arrays, with the ability of labelling columns and indexing the rows

In [68]:
# Sampling a 1000 rows 6 cols 2D array from the standard normal distribution and creating DataFrame
u = pd.DataFrame(np.random.randn(1000, 6),
                 index=np.arange(0, 3000, 3),
                 columns=['A', 'B', 'C', 'D', 'E', 'F'])

print(type(u))

u

<class 'pandas.core.frame.DataFrame'>


A         B         C         D         E         F
0    -0.920657 -0.582968 -0.585235 -0.445596 -0.681712  0.121091
3    -0.017103  0.510999  0.298593 -1.279607 -1.660310 -1.427842
6    -0.467513 -0.211803 -0.178767  0.860208  0.330933  0.128354
9     0.682888  0.578031  0.535269 -0.447142 -1.350380  1.022790
12    0.233067  1.069914 -0.672395 -0.324268 -1.213044  0.753714
...        ...       ...       ...       ...       ...       ...
2985  0.109807  1.160787  0.454515  0.761941 -0.448961 -0.549234
2988  0.289328 -0.046527 -1.958731 -0.859543 -0.004865  0.865963
2991 -2.171022 -0.993406 -0.547938  0.075995 -0.726624 -1.203640
2994 -1.542033 -1.032567 -0.546570  0.282012 -1.125996 -0.646228
2997  0.393561 -0.340553  1.729834 -0.750995  0.654371  0.932908

[1000 rows x 6 columns]

As you might have noticed, it is a bit ugly to deal with large dataframes. There are however some functions that allows to have an idea of the data in a frame.

In [69]:
u.head()

A         B         C         D         E         F
0  -0.920657 -0.582968 -0.585235 -0.445596 -0.681712  0.121091
3  -0.017103  0.510999  0.298593 -1.279607 -1.660310 -1.427842
6  -0.467513 -0.211803 -0.178767  0.860208  0.330933  0.128354
9   0.682888  0.578031  0.535269 -0.447142 -1.350380  1.022790
12  0.233067  1.069914 -0.672395 -0.324268 -1.213044  0.753714

In [70]:
u.tail()

A         B         C         D         E         F
2985  0.109807  1.160787  0.454515  0.761941 -0.448961 -0.549234
2988  0.289328 -0.046527 -1.958731 -0.859543 -0.004865  0.865963
2991 -2.171022 -0.993406 -0.547938  0.075995 -0.726624 -1.203640
2994 -1.542033 -1.032567 -0.546570  0.282012 -1.125996 -0.646228
2997  0.393561 -0.340553  1.729834 -0.750995  0.654371  0.932908

In [71]:
u.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 2997
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       1000 non-null   float64
 1   B       1000 non-null   float64
 2   C       1000 non-null   float64
 3   D       1000 non-null   float64
 4   E       1000 non-null   float64
 5   F       1000 non-null   float64
dtypes: float64(6)
memory usage: 54.7 KB


In [72]:
u.describe()

A            B            C            D            E  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.034690    -0.061913    -0.068992    -0.076187    -0.016044   
std       1.008428     1.018624     1.002010     1.018882     0.994240   
min      -3.873438    -3.581204    -2.851055    -3.334353    -3.375688   
25%      -0.627460    -0.648151    -0.720336    -0.767755    -0.639869   
50%       0.009583    -0.076407    -0.076573    -0.045585     0.017264   
75%       0.765485     0.619304     0.573383     0.619241     0.671474   
max       2.687426     3.407755     3.116299     3.093830     3.418324   

                 F  
count  1000.000000  
mean     -0.015323  
std       0.957231  
min      -2.631431  
25%      -0.711587  
50%      -0.016043  
75%       0.642756  
max       3.516588

One can also change the maximal number of rows that is displayed:

In [73]:
pd.set_option('display.max_rows', 15)

u

A         B         C         D         E         F
0    -0.920657 -0.582968 -0.585235 -0.445596 -0.681712  0.121091
3    -0.017103  0.510999  0.298593 -1.279607 -1.660310 -1.427842
6    -0.467513 -0.211803 -0.178767  0.860208  0.330933  0.128354
9     0.682888  0.578031  0.535269 -0.447142 -1.350380  1.022790
12    0.233067  1.069914 -0.672395 -0.324268 -1.213044  0.753714
...        ...       ...       ...       ...       ...       ...
2985  0.109807  1.160787  0.454515  0.761941 -0.448961 -0.549234
2988  0.289328 -0.046527 -1.958731 -0.859543 -0.004865  0.865963
2991 -2.171022 -0.993406 -0.547938  0.075995 -0.726624 -1.203640
2994 -1.542033 -1.032567 -0.546570  0.282012 -1.125996 -0.646228
2997  0.393561 -0.340553  1.729834 -0.750995  0.654371  0.932908

[1000 rows x 6 columns]

### Indexing/Slicing in Pandas

The easiest way of accessing information in a Pandas dataframe, equivalent to the way used in NumPy, is using the `iloc` command. With this you can also set specific values, do conditional indexing... all that we have seen before in section 2.4

In [74]:
# Slice-in rows index 125 to 132 (132 included!) from columns index 0, 2 and 5
u.iloc[125:132, [0, 2, 5]]

A         C         F
375  0.403273  0.198361 -0.785681
378  0.147993  1.093704 -0.153657
381 -1.061079  0.044698 -0.196515
384 -1.577289 -0.081602 -0.043167
387 -1.070241  0.943203 -0.490908
390 -0.394896  0.742236  0.992452
393 -0.294508 -0.255236  1.101463

You can also choose specific rows according to their indices with the `loc` command

In [75]:
# Slice-in rows 375 to 393 (393 included!) from columns A, C and F
u.loc[375:393, ['A', 'C', 'F']]

A         C         F
375  0.403273  0.198361 -0.785681
378  0.147993  1.093704 -0.153657
381 -1.061079  0.044698 -0.196515
384 -1.577289 -0.081602 -0.043167
387 -1.070241  0.943203 -0.490908
390 -0.394896  0.742236  0.992452
393 -0.294508 -0.255236  1.101463

The usual `[]` will select specific rows according to the row number

In [76]:
# Slice-in rows index 125 to 132 (132 included!) from columns A, C and F
u[125:132][['A', 'C', 'F']]

A         C         F
375  0.403273  0.198361 -0.785681
378  0.147993  1.093704 -0.153657
381 -1.061079  0.044698 -0.196515
384 -1.577289 -0.081602 -0.043167
387 -1.070241  0.943203 -0.490908
390 -0.394896  0.742236  0.992452
393 -0.294508 -0.255236  1.101463

However, there are a few different ways of accessing the data in a Pandas dataframe, that typically have a more "direct" connection with the actual content fo the dataframe. Individual or sets of columns can also be accessed by their column names. Choosing one single column will give a Series, while two or more will produce a DataFrame

In [77]:
u['A'].head()

0    -0.920657
3    -0.017103
6    -0.467513
9     0.682888
12    0.233067
Name: A, dtype: float64

In [78]:
u[['A', 'D']].head()

A         D
0  -0.920657 -0.445596
3  -0.017103 -1.279607
6  -0.467513  0.860208
9   0.682888 -0.447142
12  0.233067 -0.324268

Not only that, you can access a single column without the need of brackets []

In [79]:
u.A.head()

0    -0.920657
3    -0.017103
6    -0.467513
9     0.682888
12    0.233067
Name: A, dtype: float64

Or, you can access just the elements that satisfy some condition

In [80]:
u[u.D > 2]

A         B         C         D         E         F
168   0.029182 -0.055373  0.413367  2.159409 -0.107484 -0.568885
342   0.246142 -0.575288  1.183090  3.093830 -0.048119 -0.228327
771   0.225022 -0.246722  0.320646  2.989750 -0.153650  1.653815
807   2.400690 -0.000816 -0.213668  2.044642 -0.211728 -1.184668
1029 -1.521710 -0.463771  0.161482  2.145911 -1.703157 -1.081007
...        ...       ...       ...       ...       ...       ...
2454 -0.134750 -1.864866  0.036575  2.001025  1.416778 -0.223436
2661 -1.174205 -1.278691 -1.908602  2.478132 -0.696754  0.596047
2694  0.701319  1.700763  0.182507  2.736854  1.095017  0.404257
2844  1.004502 -1.572246 -0.361376  2.261472  0.130629  0.609477
2865 -0.627037 -1.778637 -0.357833  2.510799 -1.785096 -0.250410

[19 rows x 6 columns]

In [81]:
u[~(u.D > 2)]  # For the inverse of u.D > 2

A         B         C         D         E         F
0    -0.920657 -0.582968 -0.585235 -0.445596 -0.681712  0.121091
3    -0.017103  0.510999  0.298593 -1.279607 -1.660310 -1.427842
6    -0.467513 -0.211803 -0.178767  0.860208  0.330933  0.128354
9     0.682888  0.578031  0.535269 -0.447142 -1.350380  1.022790
12    0.233067  1.069914 -0.672395 -0.324268 -1.213044  0.753714
...        ...       ...       ...       ...       ...       ...
2985  0.109807  1.160787  0.454515  0.761941 -0.448961 -0.549234
2988  0.289328 -0.046527 -1.958731 -0.859543 -0.004865  0.865963
2991 -2.171022 -0.993406 -0.547938  0.075995 -0.726624 -1.203640
2994 -1.542033 -1.032567 -0.546570  0.282012 -1.125996 -0.646228
2997  0.393561 -0.340553  1.729834 -0.750995  0.654371  0.932908

[981 rows x 6 columns]

Recently `query` has been added to `DataFrame` for the same purpose. While it is less powerful than logical indexing, it is often faster and shorter (when names are longer than just `u`):

In [82]:
u.query('D > 2')

A         B         C         D         E         F
168   0.029182 -0.055373  0.413367  2.159409 -0.107484 -0.568885
342   0.246142 -0.575288  1.183090  3.093830 -0.048119 -0.228327
771   0.225022 -0.246722  0.320646  2.989750 -0.153650  1.653815
807   2.400690 -0.000816 -0.213668  2.044642 -0.211728 -1.184668
1029 -1.521710 -0.463771  0.161482  2.145911 -1.703157 -1.081007
...        ...       ...       ...       ...       ...       ...
2454 -0.134750 -1.864866  0.036575  2.001025  1.416778 -0.223436
2661 -1.174205 -1.278691 -1.908602  2.478132 -0.696754  0.596047
2694  0.701319  1.700763  0.182507  2.736854  1.095017  0.404257
2844  1.004502 -1.572246 -0.361376  2.261472  0.130629  0.609477
2865 -0.627037 -1.778637 -0.357833  2.510799 -1.785096 -0.250410

[19 rows x 6 columns]

### Reshaping `DataFrame`s

In [83]:
df1 = pd.DataFrame()

df1['sample'] = ['A', 'A', 'A', 'B', 'B', 'B']
df1['replicate'] = ['01', '02', '03', '01', '02', '03']
df1['protein'] = 'P02768'
df1['value1'] = np.random.randn(6)

df1

sample replicate protein    value1
0      A        01  P02768  1.175802
1      A        02  P02768 -0.410176
2      A        03  P02768  1.866996
3      B        01  P02768  0.035961
4      B        02  P02768 -0.414273
5      B        03  P02768 -0.084432

In [84]:
pivot_df1 = df1.pivot(index='replicate', columns='sample', values='value1')

pivot_df1.head()

sample            A         B
replicate                    
01         1.175802  0.035961
02        -0.410176 -0.414273
03         1.866996 -0.084432

### Computing With `DataFrames`

You can calculate with `DataFrames` or their columns (which are `Series`) the same way you could with `arrays`s

In [85]:
df1['value2'] = 1 / df1['value1']
df1.head()

sample replicate protein    value1     value2
0      A        01  P02768  1.175802   0.850483
1      A        02  P02768 -0.410176  -2.437978
2      A        03  P02768  1.866996   0.535620
3      B        01  P02768  0.035961  27.807872
4      B        02  P02768 -0.414273  -2.413865

In [86]:
np.mean(df1)

C:\Users\qiv\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3438: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


replicate    1.700502e+09
value1       3.616463e-01
value2       2.083038e+00
dtype: float64

You can apply functions to the whole dataset or specific columns with the `apply` command. `apply` acts on the whole column at a time (i.e. a Pandas `Series`), so you can compute things that depend on several values of the column, for instance the mean value. To apply functions in a real element-by-element basis the function `applymap` or `Series.apply` should be used.

In [87]:
def mn(col):
    return sum(col) / len(col)

df1[['value1', 'value2']].apply(mn)

value1    0.361646
value2    2.083038
dtype: float64

While most can be directly calculated (including the given example of the mean), `apply` also works on columns with strings or categorical data, where no mathematical operations are defined. The limit is the imagination.

### Combining `DataFrames`

Something we will do quite often as scientists is combining data from different sources into one single source. This can be achieved by different commands in Pandas, depending on the actual goal we want.

To begin with, appending new rows of data is achieved by the command `append`.

In [88]:
df2 = pd.DataFrame()

df2['sample'] = ['A', 'A', 'A', 'B', 'B', 'B']
df2['replicate'] = ['01', '02', '03', '01', '02', '03']
df2['protein'] = 'P69892'
df2['value1'] = np.random.randn(6)
df2['value2'] = 1 / df2['value1']

df2

sample replicate protein    value1    value2
0      A        01  P69892 -0.847244 -1.180297
1      A        02  P69892 -1.184034 -0.844570
2      A        03  P69892  0.559044  1.788767
3      B        01  P69892  0.853636  1.171460
4      B        02  P69892  0.371381  2.692653
5      B        03  P69892 -0.167774 -5.960408

In [89]:
df1.append(df2, ignore_index=True)

sample replicate protein    value1     value2
0       A        01  P02768  1.175802   0.850483
1       A        02  P02768 -0.410176  -2.437978
2       A        03  P02768  1.866996   0.535620
3       B        01  P02768  0.035961  27.807872
4       B        02  P02768 -0.414273  -2.413865
5       B        03  P02768 -0.084432 -11.843906
6       A        01  P69892 -0.847244  -1.180297
7       A        02  P69892 -1.184034  -0.844570
8       A        03  P69892  0.559044   1.788767
9       B        01  P69892  0.853636   1.171460
10      B        02  P69892  0.371381   2.692653
11      B        03  P69892 -0.167774  -5.960408

The same result can be obtained with `concat`.

In [90]:
df = pd.concat([df1, df2], ignore_index=True)

df

sample replicate protein    value1     value2
0       A        01  P02768  1.175802   0.850483
1       A        02  P02768 -0.410176  -2.437978
2       A        03  P02768  1.866996   0.535620
3       B        01  P02768  0.035961  27.807872
4       B        02  P02768 -0.414273  -2.413865
5       B        03  P02768 -0.084432 -11.843906
6       A        01  P69892 -0.847244  -1.180297
7       A        02  P69892 -1.184034  -0.844570
8       A        03  P69892  0.559044   1.788767
9       B        01  P69892  0.853636   1.171460
10      B        02  P69892  0.371381   2.692653
11      B        03  P69892 -0.167774  -5.960408

### Grouping Data

In [91]:
df.groupby('protein').agg(sum)

value1     value2
protein                     
P02768   2.169878  12.498225
P69892  -0.414992  -2.332395

In [92]:
df.groupby(['protein', 'sample']).agg(sum)

value1     value2
protein sample                     
P02768  A       2.632622  -1.051875
        B      -0.462744  13.550101
P69892  A      -1.472235  -0.236100
        B       1.057243  -2.096295

In [93]:
df.groupby(['protein', 'sample', 'replicate']).agg(sum)

value1     value2
protein sample replicate                     
P02768  A      01         1.175802   0.850483
               02        -0.410176  -2.437978
               03         1.866996   0.535620
        B      01         0.035961  27.807872
               02        -0.414273  -2.413865
               03        -0.084432 -11.843906
P69892  A      01        -0.847244  -1.180297
               02        -1.184034  -0.844570
               03         0.559044   1.788767
        B      01         0.853636   1.171460
               02         0.371381   2.692653
               03        -0.167774  -5.960408

In [94]:
df.groupby('protein').transform(np.mean)

C:\Users\qiv\AppData\Local\Temp/ipykernel_50596/96158140.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the transforming function.
  df.groupby('protein').transform(np.mean)


replicate    value1    value2
0   1.700502e+09  0.361646  2.083038
1   1.700502e+09  0.361646  2.083038
2   1.700502e+09  0.361646  2.083038
3   1.700502e+09  0.361646  2.083038
4   1.700502e+09  0.361646  2.083038
5   1.700502e+09  0.361646  2.083038
6   1.700502e+09 -0.069165 -0.388733
7   1.700502e+09 -0.069165 -0.388733
8   1.700502e+09 -0.069165 -0.388733
9   1.700502e+09 -0.069165 -0.388733
10  1.700502e+09 -0.069165 -0.388733
11  1.700502e+09 -0.069165 -0.388733

In [95]:
df.groupby('protein')['value1', 'value2'].transform(np.mean)

C:\Users\qiv\AppData\Local\Temp/ipykernel_50596/3558505644.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby('protein')['value1', 'value2'].transform(np.mean)


value1    value2
0   0.361646  2.083038
1   0.361646  2.083038
2   0.361646  2.083038
3   0.361646  2.083038
4   0.361646  2.083038
5   0.361646  2.083038
6  -0.069165 -0.388733
7  -0.069165 -0.388733
8  -0.069165 -0.388733
9  -0.069165 -0.388733
10 -0.069165 -0.388733
11 -0.069165 -0.388733

In [96]:
for g, g_df in df.groupby(['protein', 'sample']):
    print(g_df)
    print(f"{g} --> mean value1: {np.mean(g_df['value1'])}")
    print(f"      mean value2: {np.mean(g_df['value2'])}\n")

  sample replicate protein    value1    value2
0      A        01  P02768  1.175802  0.850483
1      A        02  P02768 -0.410176 -2.437978
2      A        03  P02768  1.866996  0.535620
('P02768', 'A') --> mean value1: 0.8775406031007448
      mean value2: -0.35062503903686126

  sample replicate protein    value1     value2
3      B        01  P02768  0.035961  27.807872
4      B        02  P02768 -0.414273  -2.413865
5      B        03  P02768 -0.084432 -11.843906
('P02768', 'B') --> mean value1: -0.15424800457162488
      mean value2: 4.516700189136153

  sample replicate protein    value1    value2
6      A        01  P69892 -0.847244 -1.180297
7      A        02  P69892 -1.184034 -0.844570
8      A        03  P69892  0.559044  1.788767
('P69892', 'A') --> mean value1: -0.4907448797986365
      mean value2: -0.07869991325198093

   sample replicate protein    value1    value2
9       B        01  P69892  0.853636  1.171460
10      B        02  P69892  0.371381  2.692653
11      B

In [97]:
df.groupby(['protein', 'sample']).describe()

value1                                                    \
                count      mean       std       min       25%       50%   
protein sample                                                            
P02768  A         3.0  0.877541  1.167518 -0.410176  0.382813  1.175802   
        B         3.0 -0.154248  0.233096 -0.414273 -0.249353 -0.084432   
P69892  A         3.0 -0.490745  0.924608 -1.184034 -1.015639 -0.847244   
        B         3.0  0.352414  0.510969 -0.167774  0.101804  0.371381   

                                   value2                                  \
                     75%       max  count      mean        std        min   
protein sample                                                              
P02768  A       1.521399  1.866996    3.0 -0.350625   1.814543  -2.437978   
        B      -0.024235  0.035961    3.0  4.516700  20.714498 -11.843906   
P69892  A      -0.144100  0.559044    3.0 -0.078700   1.625962  -1.180297   
        B       0.612508  0.853636    3.0 -0.698765   4.619759  -5.960408   

                                                          
                     25%       50%        75%        max  
protein sample                                            
P02768  A      -0.951179  0.535620   0.693052   0.850483  
        B      -7.128886 -2.413865  12.697004  27.807872  
P69892  A      -1.012433 -0.844570   0.472099   1.788767  
        B      -2.394474  1.171460   1.932056   2.692653

In [98]:
df.pivot_table(index='protein',
               columns='sample', 
               aggfunc='mean')

value1              value2          
sample          A         B         A         B
protein                                        
P02768   0.877541 -0.154248 -0.350625  4.516700
P69892  -0.490745  0.352414 -0.078700 -0.698765

In [99]:
df.pivot_table(index='protein',
               columns='sample',
               aggfunc={'value1': min,
                        'value2': max})

value1              value2           
sample          A         B         A          B
protein                                         
P02768  -0.410176 -0.414273  0.850483  27.807872
P69892  -1.184034 -0.167774  1.788767   2.692653

### Loading and saving dataframes

To load and save Pandas dataframes we will use the `to_csv` and `read_csv` commands

In [100]:
df.to_csv('test.csv')
pd.read_csv('test.csv', index_col=0)

sample  replicate protein    value1     value2
0       A          1  P02768  1.175802   0.850483
1       A          2  P02768 -0.410176  -2.437978
2       A          3  P02768  1.866996   0.535620
3       B          1  P02768  0.035961  27.807872
4       B          2  P02768 -0.414273  -2.413865
5       B          3  P02768 -0.084432 -11.843906
6       A          1  P69892 -0.847244  -1.180297
7       A          2  P69892 -1.184034  -0.844570
8       A          3  P69892  0.559044   1.788767
9       B          1  P69892  0.853636   1.171460
10      B          2  P69892  0.371381   2.692653
11      B          3  P69892 -0.167774  -5.960408

But, as an addition, Pandas has special commands to load and save Excel spreadsheets (yay!). However, to use it you'll need the `openpyxl` and `xlrd` packages.

In [101]:
df.to_excel('test.xlsx', sheet_name='My sheet')
pd.read_excel('test.xlsx', 'My sheet', index_col=0)

sample  replicate protein    value1     value2
0       A          1  P02768  1.175802   0.850483
1       A          2  P02768 -0.410176  -2.437978
2       A          3  P02768  1.866996   0.535620
3       B          1  P02768  0.035961  27.807872
4       B          2  P02768 -0.414273  -2.413865
5       B          3  P02768 -0.084432 -11.843906
6       A          1  P69892 -0.847244  -1.180297
7       A          2  P69892 -1.184034  -0.844570
8       A          3  P69892  0.559044   1.788767
9       B          1  P69892  0.853636   1.171460
10      B          2  P69892  0.371381   2.692653
11      B          3  P69892 -0.167774  -5.960408

**Exercise 5**: Download [this dataset](https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv) and load it, using the first column as the index. Take a look at it, and do the following things:
- Choose the columns 'Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1' and 'Type2' 
- Create a function that lowercases strings and apply it to 'Type1' and 'Type2' (*Extra: just capitalize the strings, i.e., leave the first letter uppercase and lowercase the rest*)
- Create a function that returns a Boolean value (don't be afraif by this, it is a function that returns either True or False) that tells if a Pokémon has high stamina (BaseStamina>170) or not. Store this information in a new column and show the list of Pokémon with high stamina
- Show the instructor the last 15 rows of your dataset

In [102]:
df = pd.read_csv('https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv', 
                 index_col=0)

df = df[['Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1', 'Type2']]

capitalize = lambda st: st.capitalize()

for col in ['Type1', 'Type2']:
    df[col] = df[col].apply(capitalize)
    
def highstamina(x):
    return True if x > 170 else False

df['HighStamina'] = df.BaseStamina.apply(highstamina)

print(df[df['HighStamina'] == True].Identifier)

df.tail(15)

PkMn
31      Nidoqueen
36       Clefable
39     Jigglypuff
40     Wigglytuff
59       Arcanine
          ...    
145        Zapdos
146       Moltres
149     Dragonite
150        Mewtwo
151           Mew
Name: Identifier, Length: 26, dtype: object


Identifier  BaseStamina  BaseAttack  BaseDefense     Type1   Type2  \
PkMn                                                                       
137      Porygon          130         156          158    Normal    None   
138      Omanyte           70         132          160      Rock   Water   
139      Omastar          140         180          202      Rock   Water   
140       Kabuto           60         148          142      Rock   Water   
141     Kabutops          120         190          190      Rock   Water   
142   Aerodactyl          160         182          162      Rock  Flying   
143      Snorlax          320         180          180    Normal    None   
144     Articuno          180         198          242       Ice  Flying   
145       Zapdos          180         232          194  Electric  Flying   
146      Moltres          180         242          194      Fire  Flying   
147      Dratini           82         128          110    Dragon    None   
148    Dragonair          122         170          152    Dragon    None   
149    Dragonite          182         250          212    Dragon  Flying   
150       Mewtwo          212         284          202   Psychic    None   
151          Mew          200         220          220   Psychic    None   

      HighStamina  
PkMn               
137         False  
138         False  
139         False  
140         False  
141         False  
142         False  
143          True  
144          True  
145          True  
146          True  
147         False  
148         False  
149          True  
150          True  
151          True