# 4 NumPy and Pandas

## Introduction

After getting used to how Python works, it is the moment to begin getting our hands dirty with data analysis. We will study two packages: [NumPy](http://www.numpy.org/) is the fundamental numeric computing and linear algebra package in Python, that allows for decent data analysis. We will learn it not only for the data analysis, but more importantly because it will be a package that will be always present in our `import` section as scientists. After NumPy we will go to [Pandas](http://pandas.pydata.org/). Pandas is a dedicated data analysis package with a lot more functionalities than NumPy, making our life much easier in terms of data visualization and manipulation. All the power of Pandas will be completely unleashed in Section 5, where we will see how to visualize information in plots.

As usual, we begin importing the necessary packages

In [1]:
import numpy as np
import pandas as pd
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 1.15.0
Pandas: 0.23.4


## Numeric Python (NumPy)

NumPy is an open-source add-on module to Python that provides common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that
associated with common commercial software like MATLAB. The [NumPy](http://www.numpy.org/) (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. The main object NumPy works with is a *homogeneous multidimensional array*. Despite its intimidating name, these are nothing but tables of numbers, each labelled by a tuple of indices.

We will now explore some capabilities of NumPy that will prove very useful not only for data analyisis, but throughout all our life with Python.

### Creating Arrays

As mentioned before, the main object in NumPy is the *array*. Creating one is as easy as calling the command `array`

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
type(x)

numpy.ndarray

The same applies to multidimensional arrays

In [4]:
m = np.array([[[7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6]]])
m

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

There is one restriction with respect to the use of lists: while you could create lists with data of different type, all the data in an array has to be of the same type, and it will be converted automatically.

In [5]:
lst = [1., 'cat']
print(type(lst[0]))

arr = np.array(lst)
print(type(arr[0]))

<class 'float'>
<class 'numpy.str_'>


(We will go deeper into indexing in a while)

-----
A NumPy array has a number of dimensions (or *axes*). To obtain the number of axes and the size of each of them you use the command `shape`. For 2-dimensional arrays (matrices), the order corresponds to (rows, columns)

There are two different ways of calling the `shape` command, either with `np.shape(arr)` or `arr.shape`. This is not the only command that works in both formats, and we will be finding some more in our way.

In [6]:
print(x.shape)
print(np.shape(m))

(3,)
(2, 2, 3)


### Special Arrays

Now we review some built-in functions that create matrices commonly used. `ones` and `zeros` return arrays of given shape and type (default is float64), filled with ones or zeros, respectively.

In [7]:
array_zeros=np.zeros((3, 2))
array_ones=np.ones((3, 2, 4), dtype=np.int8)

In [8]:
array_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
array_ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

`eye(d)` returns a 2-D, dimension-$d$ array with ones on the diagonal and zeros elsewhere.

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`eye` can also create arrays with ones in upper and lower diagonals. To achieve this, you must call `eye(d, d, k)` where $k$ denotes the diagonal (positive for above the center diagonal, negative for below), or `eye(d, k=num)`

In [11]:
print(np.eye(5, 5, 2))
np.eye(5, k=-1)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

`diag`, depending on the input, either extracts a diagonal from a matrix (if the input is a 2-D array), or constructs a diagonal array (if the input is a vector).

In [12]:
np.diag(x, 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [13]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np.diag(y))
np.diag(np.diag(y))

[ 1  6 11 16]


array([[ 1,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 16]])

`arange(begin, end, step)` returns evenly spaced values within a given interval. Note that the beginning point is included, but not the ending.

In [14]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
len(n)

15

**Exercise 1**: Create an array of the first million of odd numbers, both with `arange` and using loops. Try timing both methods to see which one is faster. For that, use `%timeit`.

In [16]:
%timeit np.arange(0, 2e6, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

473 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
88 ms ± 631 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Similarly, `linspace(begin, end, points)` returns evenly spaced numbers over a specified interval. Here, instead of specifying the step, you specify the amount of points you want. Also with `linspace` you include the ending of the interval.

In [17]:
o = np.linspace(0, 30, 15)
o

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        , 17.14285714, 19.28571429,
       21.42857143, 23.57142857, 25.71428571, 27.85714286, 30.        ])

In [18]:
len(o)

15

`reshape` changes the shape of an array, but not its data. This is another of the commands that can be called before or after the array.

In [19]:
print(n.reshape(3, 5))
np.reshape(n, (5, 3))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

Note however that, in order for these changes to be permanent, you should do a reassignment of the variable

In [20]:
print(n)  # After the reshapings above, the original array stays being the same

n = n.reshape(3, 5)
n   # Now that we have reassigned it is when it definitely changes shape

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### Combining Arrays

The most general command for combining arrays is `concatenate(arrs, d)`. It takes a list of arrays and concatenates them along axis $d$

In [21]:
p = np.ones([2, 2, 2])
p

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [22]:
np.concatenate([p, 2 * p], 0)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [23]:
np.concatenate([p, 2 * p], 1)

array([[[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]],

       [[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]]])

In [24]:
np.concatenate([p, 2 * p], 2)

array([[[1., 1., 2., 2.],
        [1., 1., 2., 2.]],

       [[1., 1., 2., 2.],
        [1., 1., 2., 2.]]])

However, for common combinations there exist special commands. Use `vstack` to stack arrays in sequence vertically (row wise), `hstack` to stack arrays in sequence horizontally (column wise), and `block` to create arrays out of blocks (only available in versions 1.13.0+)

In [25]:
q = np.ones((2, 2))
np.vstack([q, 2 * q])

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.]])

In [26]:
np.hstack([q, 2 * q])

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.]])

In [27]:
np.block([[q, np.zeros((2, 2))], [np.zeros((2, 2)), 2 * q]])

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 2., 2.],
       [0., 0., 2., 2.]])

### Operations

You can perform easily element-wise operations on arrays of any shape. Use the typical symbols, +, -, \*, / and \*\* to perform element-wise addition, subtraction, multiplication, division and power.

In [28]:
x = np.array([1, 2, 3])
print(x)
print(x + 10)
print(3 * x)
print(1 / x)
print(x ** (-2 / 3))
print(2 ** x)

[1 2 3]
[11 12 13]
[3 6 9]
[1.         0.5        0.33333333]
[1.         0.62996052 0.48074986]
[2 4 8]


Also (and obviously) these symbols can be used to operate between two arrays, which must be of the same shape. If this is the case, they also do element-wise operations

In [29]:
y = np.arange(4, 7, 1)
print(x + y)     # [1+4, 2+5, 3+6]
print(x * y)     # [1*4, 2*5, 3*6]
print(x / y)     # [1/4, 2/5, 3/6]
print(x ** y)    # [1**4, 2**5, 3**6]

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


For doing vector or matrix multiplication, the command to be used is `dot`

In [30]:
x.dot(y) # 1*4 + 2*5 + 3*6

32

With python 3.5 matrix multiplication got it's own operator

In [31]:
x@y

32

In [32]:
X = np.array([[i + j for i in range(3, 6)] for j in range(3)])
Y = np.diag([1, 1], 1) + np.diag([1], -2)

print('{}\n'.format(X))
print(X * Y)
np.dot(X, Y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]

[[0 4 0]
 [0 0 6]
 [5 0 0]]


array([[5, 3, 4],
       [6, 4, 5],
       [7, 5, 6]])

**Exercise 2**: Take a 10x2 matrix representing $(x1,x2)$ coordinates and transform them into polar coordinates $(r,\theta)$.

*Hint 1: the inverse transformation is given by $x1 = r\cos\theta$, $x2 = r\sin\theta$*

*Hint 2: generate random numbers with the functions in numpy.random*

In [33]:
z = np.random.random((10, 2))
x1, x2 = z[:, 0], z[:, 1]
R = np.sqrt(x1 ** 2 + x2 ** 2)
T = np.arctan2(x2, x1)
print(R)
print(T)

[0.69254624 0.69830701 0.57132173 0.89188587 0.29925014 0.28653816
 1.24824649 0.89788709 0.78615101 1.00057153]
[1.47063331 0.62256783 0.06639133 0.5449192  1.46714486 0.37345224
 0.81141022 0.03207796 1.21337778 1.36550297]


#### Transposing

Transposition is a very important operation for linear algebra. Although NumPy is capable of correctly doing matrix-vector products correctly regardless of the orientation of the vector, it is not the case for products of matrices

In [34]:
Z = np.arange(0, 12, 1).reshape((4, 3))

In [35]:
np.dot(Z, y)

array([ 17,  62, 107, 152])

In [36]:
np.dot(Z, y.T)

array([ 17,  62, 107, 152])

In [37]:
Z.dot(X)

array([[ 14,  17,  20],
       [ 50,  62,  74],
       [ 86, 107, 128],
       [122, 152, 182]])

In [38]:
(Z.T).dot(X)

ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

#### Array Methods

To not have to go from NumPy arrays to lists back and forth, NumPy contains some functions to know properties of your arrays. Actually, there are more of these functions than in standard Python.

In [39]:
a = np.array([-4, -2, 1, 3, 5])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

5
-4
3
0.6
3.2619012860600183


Some interesting functions are `argmax` and `argmin`, which return the index of the maximum and minimum values in the array.

In [40]:
print(a.argmax())
print(a.argmin())

4
0


### Indexing/Slicing

We have already seen briefly that to access individual elements you use the bracket notation: `array[ax_0, ax_1, ...]`, where the `ax_i` denotes the coordinate in the `i`-th axis. You can even use this to assign new values to your elements.

In [41]:
r = [4, 5, 6, 7]
print(r[2])
r[0] = 198
r

6


[198, 5, 6, 7]

To select a range of rows or columns you can use a colon :. A second : can be used to indicate the step size. `array[start:stop:stepsize]`. If you leave `start` (`stop`) blank, the selection will go from the very beginning (until the very end) of the array

In [42]:
s = np.arange(13)**2
print(s)
print(s[3:9])
print(s[2:10:3])
s[-5::-2]

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[ 9 16 25 36 49 64]
[ 4 25 64]


array([64, 36, 16,  4,  0])

The same applies to matrices or higher-dimensional arrays

In [43]:
r = np.arange(36).reshape((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [44]:
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

You can also select specific rows and columns, separated by commas

In [45]:
r[[1, 3, 4], 1:3]

array([[ 7,  8],
       [19, 20],
       [25, 26]])

A very useful tool is *conditional indexing*, where we apply a function, assignment... only to those elements of an array that satisfy some condition

In [46]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Exercise 3**: Create a random 1-dimensional array, and find which element is closest to 0.7

In [47]:
Z = np.random.uniform(0,1,100)
z = 0.7
m = Z[np.abs(Z - z).argmin()]
print(m)

0.6963990158401812


#### Copying Data

**Be very careful with copying and modifying arrays in NumPy!** You will see the reason right now. Let's begin defining `r2` as a slice of r

In [48]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

And now let's set all its elements to zero

In [49]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

When looking at `r`, we see that it has also been changed!

In [50]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

The proper way of handling selections without modifying the original arrays is through the `copy` command.

In [51]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now we can safely modify `r_copy` without affecting `r`.

In [52]:
r_copy[:] = 10
print('{}\n'.format(r_copy))
r

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]



array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Iterating Over Arrays

Finally, you can iterate over arrays in the same way as you iterate over lists

In [53]:
test = np.random.randint(0, 10, (4,3))
test

array([[6, 7, 8],
       [7, 6, 1],
       [2, 3, 5],
       [2, 3, 1]])

You can iterate by row:

In [54]:
for row in test:
    print(row)

[6 7 8]
[7 6 1]
[2 3 5]
[2 3 1]


Or by row index

In [55]:
for i in range(len(test)):
    print(test[i])

[6 7 8]
[7 6 1]
[2 3 5]
[2 3 1]


Or by row and index:

In [56]:
for i, row in enumerate(test):
    print('Row {} is {}'.format(i, row))

Row 0 is [6 7 8]
Row 1 is [7 6 1]
Row 2 is [2 3 5]
Row 3 is [2 3 1]


In the same way as with lists, you can use `zip` to iterate over multiple iterables.

In [57]:
test2 = test**2
test2

array([[36, 49, 64],
       [49, 36,  1],
       [ 4,  9, 25],
       [ 4,  9,  1]])

In [58]:
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[6 7 8] + [36 49 64] = [42 56 72]
[7 6 1] + [49 36  1] = [56 42  2]
[2 3 5] + [ 4  9 25] = [ 6 12 30]
[2 3 1] + [4 9 1] = [ 6 12  2]


**Exercise 4**: Create a function that iterates over the columns of a 2-dimensional array

In [59]:
def iterate(df):
    for i, row in enumerate(df):
        shp = row.shape
        row.shape = shp + (1,)
        print('Column {} is {}'.format(i, row))

iterate(test.T)

Column 0 is [[6]
 [7]
 [2]
 [2]]
Column 1 is [[7]
 [6]
 [3]
 [3]]
Column 2 is [[8]
 [1]
 [5]
 [1]]


### Loading and Saving Data

To load and save data NumPy has the `loadtxt` and `savetxt` commands. However, they only work for two-dimensional arrays

In [60]:
np.savetxt('numpytest.txt', test)
np.loadtxt('numpytest.txt')

array([[6., 7., 8.],
       [7., 6., 1.],
       [2., 3., 5.],
       [2., 3., 1.]])

## Pandas

When dealing with numeric matrices and vectors in Python, NumPy makes life a lot easier. For more complex data, however, it leaves a bit to be desired. For those used to working with dedicated languages like R, doing data analysis directly with numpy feels like a step back. Fortunately, some nice folks have written the Python Data Analysis Library (a.k.a. [pandas](http://pandas.pydata.org/)). Pandas provides an R-like DataFrame, produces high quality plots with matplotlib, and integrates nicely with other libraries that expect NumPy arrays.

Pandas works with `Series` of data, that then are arranged in `DataFrame`s. A dataframe will be the object closest to an Excel spreadsheet that you will see throughout the course (but of course, given that it is integrated in Python and can be combined with so many different packages, dataframes are much more powerful than Excel spreadsheets). The data in the series can be either qualitative or quantitative data. Creating a series is as easy as creating a NumPy array from a one-dimensional list.

In [61]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [62]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

Notice that the series is indexed by default by integers. You can change this indexing by using a dictionary instead of a list for creating the series.

In [63]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

On the other hand, `DataFrame`s can be built from two-dimensional arrays, with the ability of labelling columns and indexing the rows

In [64]:
u = pd.DataFrame(np.random.randn(1000,6), index=np.arange(0, 3000, 3), 
                 columns=['A', 'B', 'C', 'D', 'E', 'F'])
u

A         B         C         D         E         F
0    -0.656352 -1.828935  1.356624 -2.031876  0.714026  0.322131
3    -0.731898 -0.040749  2.087230 -0.186705  0.925189 -0.028877
6     0.279463 -0.903286  0.542951  0.245455  0.736812  0.523788
9     0.517327  0.176194  0.106239 -2.695502 -0.318348 -0.046300
12   -0.657431 -0.841408 -1.749269  0.056158  0.171432 -0.185184
15   -1.037143  0.993396 -0.460049 -0.727853  0.166404  0.770176
18   -1.154023 -0.686064  0.810068 -0.190371  0.958805  1.154928
21   -0.914291  0.224959 -0.658206  0.519325 -1.308979  0.584807
24    1.628173 -0.720387  0.026391 -0.730022 -0.307067  0.607703
27   -1.441548 -1.112996 -0.461846 -0.284627  0.312223  0.981884
30   -0.947833  0.504739 -0.185189 -0.915074  0.229380  0.950733
33    0.568704 -1.389992  1.060209 -2.030606 -1.889857 -0.653558
36   -0.216113 -0.156034  1.933680 -0.522886  0.591404  0.029560
39    0.435046 -0.544043  1.637750  2.895750  1.379531  0.798775
42   -1.387401  1.338303  0.575036  1.903666 -1.222214  0.913095
45    0.043583  1.872543  1.121038  0.506077 -1.575384 -0.688967
48   -0.024903 -0.564044  1.552075  1.876975  0.645534 -0.864259
51    0.718277 -1.142199  2.006196  0.889505 -1.922738 -1.291521
54    0.794272 -0.946418 -0.274722 -1.416130  0.660384  0.159691
57    0.260719  1.146021  0.632784 -0.871521 -0.015575 -0.180701
60    1.030691 -0.106644 -0.732406 -0.502540 -0.341653 -1.179198
63    2.530912 -0.733424  0.928991  1.054350  0.789200  0.789650
66    1.636331  1.130697 -0.850719  1.471830 -1.873937 -2.008805
69    0.397095  1.751420  0.445183 -0.780480  1.585932  1.137160
72    1.132345 -0.023577  0.071814  1.007650  0.129902  0.049196
75    0.333982  0.236107  0.635188  1.849073 -1.798078  0.049288
78    1.019885 -1.843097 -3.298523 -0.140224  0.971712  1.667694
81   -1.008793  0.670729  1.083114 -1.600656  0.909832 -0.877123
84   -0.303486  0.088631  1.389573 -0.563821 -1.755843 -1.314920
87    1.310600  0.876379 -2.317219  0.963812 -1.570543  0.507540
...        ...       ...       ...       ...       ...       ...
2910 -0.528498  1.581053  1.286878 -1.025929  0.801995  1.095970
2913  0.388897 -1.146886  1.076750  0.289971 -0.487025 -0.651288
2916 -0.308890  0.203227  0.921380 -0.958388 -0.946860  0.245081
2919 -2.233455 -0.624194  0.659391  0.685796  1.117574  1.225124
2922 -0.888760 -0.957599 -0.207529 -0.849583  0.429894  0.130599
2925  0.755002 -0.752930  0.327339 -0.590601  0.419428 -0.787615
2928  1.375938 -1.317993  1.328645 -0.563896  0.083813  0.542842
2931 -0.044718  0.790248  0.420722  0.994663  0.254418 -1.143327
2934  0.066534  0.248576 -1.932202 -0.634495  0.253297 -0.043896
2937 -0.810081  0.196221 -0.906477  0.014183  0.132089 -0.714560
2940  0.578489  0.687239 -0.836666 -1.466127  0.208678  0.894421
2943 -0.655296 -0.660953  0.896690 -0.690608 -1.096920 -2.059588
2946  1.613580  2.678219 -1.777081 -0.270872 -0.489450 -0.493806
2949 -0.478901 -0.860028 -0.340989 -0.260792  2.734018 -0.645707
2952  0.547063  0.607223  0.267722 -0.752940 -0.124947 -0.837595
2955 -0.172851 -0.930117 -0.110616  2.308126  0.192292  0.063374
2958  1.078689  2.337766  0.739069 -1.583211 -0.318322  0.982989
2961  0.013385 -0.230946  1.112972 -0.971575  0.667050  1.328941
2964  0.682707  0.668586 -0.299152  0.778902  2.846381 -0.774174
2967  0.163111  1.517941  0.162560  0.708776 -1.574712  1.029939
2970 -1.241298 -1.225870 -0.736026  0.544167  0.466127  1.869085
2973 -0.296662  1.044049 -1.000297 -0.536798  3.037953  0.133445
2976  0.381042 -0.960889 -0.039585  2.300440 -0.901716 -1.267716
2979  0.367820 -0.089890  1.165992 -1.048818  0.474310  0.042712
2982  0.037483  0.878178 -0.245404 -0.800555  1.433961  1.664625
2985 -1.443039 -0.873042  0.286502  0.131774 -0.812787 -0.432542
2988  0.636137 -0.465677  0.677833 -0.541540 -0.302328 -0.929792
2991  1.428879 -0.855440  0.539704 -1.497891  0.004913  0.093641
2994  0.746677  0.246700  0.726296  1.238024  0.333257 -1.383022
2997  2.054665  0.848563 -0.652124 -1.153524 -0.

As you might have noticed, it is a bit ugly to deal with large dataframes. There are however some functions that allows to have an idea of the data in a frame.

In [65]:
u.head()

A         B         C         D         E         F
0  -0.656352 -1.828935  1.356624 -2.031876  0.714026  0.322131
3  -0.731898 -0.040749  2.087230 -0.186705  0.925189 -0.028877
6   0.279463 -0.903286  0.542951  0.245455  0.736812  0.523788
9   0.517327  0.176194  0.106239 -2.695502 -0.318348 -0.046300
12 -0.657431 -0.841408 -1.749269  0.056158  0.171432 -0.185184

In [66]:
u.tail()

A         B         C         D         E         F
2985 -1.443039 -0.873042  0.286502  0.131774 -0.812787 -0.432542
2988  0.636137 -0.465677  0.677833 -0.541540 -0.302328 -0.929792
2991  1.428879 -0.855440  0.539704 -1.497891  0.004913  0.093641
2994  0.746677  0.246700  0.726296  1.238024  0.333257 -1.383022
2997  2.054665  0.848563 -0.652124 -1.153524 -0.171251 -0.056290

In [67]:
u.describe()

A            B            C            D            E  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.021276    -0.015718    -0.001859     0.009421    -0.017174   
std       0.978987     1.019808     0.992385     0.989330     0.991654   
min      -3.388593    -2.991824    -3.298523    -2.706775    -2.871235   
25%      -0.645020    -0.714591    -0.711553    -0.688415    -0.662433   
50%       0.013383    -0.030724    -0.006858    -0.011506     0.004806   
75%       0.712798     0.639428     0.718376     0.685899     0.662050   
max       3.761690     3.445405     3.179276     3.255549     3.037953   

                 F  
count  1000.000000  
mean      0.051858  
std       1.019828  
min      -2.988653  
25%      -0.619081  
50%       0.087382  
75%       0.762712  
max       3.512409

One can also change the maximal number of rows that is displayed:

In [68]:
pd.set_option('display.max_rows', 15)

`Pandas` can also generate random `DataFrames` for testing:

In [69]:
import pandas.util.testing as tm

tm.makeDataFrame().head()

A         B         C         D
IMkPQoYk8c -0.524647  1.590209  1.635992  2.214842
XkE2GTueIU  0.004372 -0.504213  0.960424 -0.060892
AgJDnr0Bun  0.874894  0.042252 -0.681422  0.652912
eA4yB0V0Y4 -1.697171  0.586966  0.364229  0.719895
TQB9Pnno30  0.463265  0.313215 -0.865998 -0.094642

### Indexing/Slicing in Pandas

The easiest way of accessing information in a Pandas dataframe, equivalent to the way used in NumPy, is using the `iloc` command. With this you can also set specific values, do conditional indexing... all that we have seen before in section 2.4

In [70]:
u.iloc[125:132,[0, 2, 5]]

A         C         F
375  0.047315 -1.462825 -0.449300
378  2.132679  0.117482  1.993029
381 -0.323788 -0.948980  0.780710
384  0.717457  0.439078  0.921090
387 -0.196388 -1.221562 -0.949684
390 -0.327326 -0.667344  0.693266
393  1.961462 -0.890454 -0.931758

However, there are a few different ways of accessing the data in a Pandas dataframe, that typically have a more "direct" connection with the actual content fo the dataframe. Individual or sets of columns can also be accessed by their column names. Choosing one single column will give a Series, while two or more will produce a Dataset

In [71]:
u['A'].head()

0    -0.656352
3    -0.731898
6     0.279463
9     0.517327
12   -0.657431
Name: A, dtype: float64

In [72]:
u[['A', 'D']].head()

A         D
0  -0.656352 -2.031876
3  -0.731898 -0.186705
6   0.279463  0.245455
9   0.517327 -2.695502
12 -0.657431  0.056158

Not only that, you can access a single column without the need of brackets []

In [73]:
u.A.head()

0    -0.656352
3    -0.731898
6     0.279463
9     0.517327
12   -0.657431
Name: A, dtype: float64

The usual [] will select specific rows according to the row number

In [74]:
u[0:10][list('BCF')]

B         C         F
0  -1.828935  1.356624  0.322131
3  -0.040749  2.087230 -0.028877
6  -0.903286  0.542951  0.523788
9   0.176194  0.106239 -0.046300
12 -0.841408 -1.749269 -0.185184
15  0.993396 -0.460049  0.770176
18 -0.686064  0.810068  1.154928
21  0.224959 -0.658206  0.584807
24 -0.720387  0.026391  0.607703
27 -1.112996 -0.461846  0.981884

You can also choose specific rows according to their indices with the `loc` command

In [75]:
u.loc[6:15]

A         B         C         D         E         F
6   0.279463 -0.903286  0.542951  0.245455  0.736812  0.523788
9   0.517327  0.176194  0.106239 -2.695502 -0.318348 -0.046300
12 -0.657431 -0.841408 -1.749269  0.056158  0.171432 -0.185184
15 -1.037143  0.993396 -0.460049 -0.727853  0.166404  0.770176

Or, you can access just the elements that satisfy some condition

In [76]:
u[u.D > 2]

A         B         C         D         E         F
39    0.435046 -0.544043  1.637750  2.895750  1.379531  0.798775
99   -0.094774 -0.665736  1.552407  2.484055  1.136062  0.736097
306   0.092871 -1.361800  0.338033  2.363529 -0.908800  1.423810
825  -0.888468 -0.266553  0.818580  2.878886  0.828940  0.016108
870   0.222661 -1.034132  0.212929  2.097422  0.629296  0.326917
888  -0.153532  1.212852  0.568124  2.472144  0.888389 -2.479979
990   0.859739  1.685374 -0.291760  2.646811  1.512756 -0.023077
...        ...       ...       ...       ...       ...       ...
2514  2.282413 -2.456859 -0.788048  2.768054 -0.077328  1.039673
2721  0.491507  0.291946 -0.985068  2.708964 -0.535695  1.716421
2748 -0.155888 -0.747057  2.140343  2.173648 -1.742419 -0.411200
2820  0.715476 -0.082398  0.190740  2.420269 -0.346754 -2.488403
2898 -0.611926 -1.698457 -0.698390  2.390378 -1.492945  0.692597
2955 -0.172851 -0.930117 -0.110616  2.308126  0.192292  0.063374
2976  0.381042 -0.960889 -0.039585  2.300440 -0.901716 -1.267716

[24 rows x 6 columns]

In [77]:
u[~(u.D > 2)]  # For the inverse of u.D > 2

A         B         C         D         E         F
0    -0.656352 -1.828935  1.356624 -2.031876  0.714026  0.322131
3    -0.731898 -0.040749  2.087230 -0.186705  0.925189 -0.028877
6     0.279463 -0.903286  0.542951  0.245455  0.736812  0.523788
9     0.517327  0.176194  0.106239 -2.695502 -0.318348 -0.046300
12   -0.657431 -0.841408 -1.749269  0.056158  0.171432 -0.185184
15   -1.037143  0.993396 -0.460049 -0.727853  0.166404  0.770176
18   -1.154023 -0.686064  0.810068 -0.190371  0.958805  1.154928
...        ...       ...       ...       ...       ...       ...
2979  0.367820 -0.089890  1.165992 -1.048818  0.474310  0.042712
2982  0.037483  0.878178 -0.245404 -0.800555  1.433961  1.664625
2985 -1.443039 -0.873042  0.286502  0.131774 -0.812787 -0.432542
2988  0.636137 -0.465677  0.677833 -0.541540 -0.302328 -0.929792
2991  1.428879 -0.855440  0.539704 -1.497891  0.004913  0.093641
2994  0.746677  0.246700  0.726296  1.238024  0.333257 -1.383022
2997  2.054665  0.848563 -0.652124 -1.153524 -0.171251 -0.056290

[976 rows x 6 columns]

Recently `query` has been added to `DataFrame` for the same purpose. While it is less powerful than logical indexing, it is often faster and shorter (when names are longer than just `u`):

In [78]:
u.query('D > 2')

A         B         C         D         E         F
39    0.435046 -0.544043  1.637750  2.895750  1.379531  0.798775
99   -0.094774 -0.665736  1.552407  2.484055  1.136062  0.736097
306   0.092871 -1.361800  0.338033  2.363529 -0.908800  1.423810
825  -0.888468 -0.266553  0.818580  2.878886  0.828940  0.016108
870   0.222661 -1.034132  0.212929  2.097422  0.629296  0.326917
888  -0.153532  1.212852  0.568124  2.472144  0.888389 -2.479979
990   0.859739  1.685374 -0.291760  2.646811  1.512756 -0.023077
...        ...       ...       ...       ...       ...       ...
2514  2.282413 -2.456859 -0.788048  2.768054 -0.077328  1.039673
2721  0.491507  0.291946 -0.985068  2.708964 -0.535695  1.716421
2748 -0.155888 -0.747057  2.140343  2.173648 -1.742419 -0.411200
2820  0.715476 -0.082398  0.190740  2.420269 -0.346754 -2.488403
2898 -0.611926 -1.698457 -0.698390  2.390378 -1.492945  0.692597
2955 -0.172851 -0.930117 -0.110616  2.308126  0.192292  0.063374
2976  0.381042 -0.960889 -0.039585  2.300440 -0.901716 -1.267716

[24 rows x 6 columns]

### Computing With `DataFrames`

You can calculate with `DataFrames` or their columns (which are `Series`) the same way you could with `arrays`s

In [79]:
u['F'] = 1 / u['F']
u['F'].head()

0      3.104331
3    -34.629224
6      1.909168
9    -21.598144
12    -5.400024
Name: F, dtype: float64

In [80]:
np.mean(u)

A    0.021276
B   -0.015718
C   -0.001859
D    0.009421
E   -0.017174
F    1.123963
dtype: float64

You can apply functions to the whole dataset or specific columns with the `apply` command. `apply` acts on the whole column at a time (i.e. a Pandas `Series`), so you can compute things that depend on several values of the column, for instance the mean value. To apply functions in a real element-by-element basis the function `applymap` or `Series.apply` should be used.

In [81]:
def mn(col):
    return sum(col) / len(col)

u.apply(mn)

A    0.021276
B   -0.015718
C   -0.001859
D    0.009421
E   -0.017174
F    1.123963
dtype: float64

While most can be directly calculated (including the given example of the mean), `apply` also works on columns with strings or categorical data, where no mathematical operations are defined. The limit is the imagination.

### Combining `DataFrames`

Something we will do quite often as scientists is combining data from different sources into one single source. This can be achieved by different commands in Pandas, depending on the actual goal we want.

To begin with, appending new rows of data is achieved by the command `append`.

In [82]:
newdata = pd.DataFrame(np.ones((5, 6)), index=np.arange(3003, 3018, 3), columns=list('ABCDEF'))
newdata

A    B    C    D    E    F
3003  1.0  1.0  1.0  1.0  1.0  1.0
3006  1.0  1.0  1.0  1.0  1.0  1.0
3009  1.0  1.0  1.0  1.0  1.0  1.0
3012  1.0  1.0  1.0  1.0  1.0  1.0
3015  1.0  1.0  1.0  1.0  1.0  1.0

In [83]:
unew = u.append(newdata)
unew.tail(10)

A         B         C         D         E          F
2985 -1.443039 -0.873042  0.286502  0.131774 -0.812787  -2.311916
2988  0.636137 -0.465677  0.677833 -0.541540 -0.302328  -1.075509
2991  1.428879 -0.855440  0.539704 -1.497891  0.004913  10.679053
2994  0.746677  0.246700  0.726296  1.238024  0.333257  -0.723054
2997  2.054665  0.848563 -0.652124 -1.153524 -0.171251 -17.765266
3003  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000

The same result can be obtained with `concat`.

In [84]:
pd.concat([u, newdata]).tail(10)

A         B         C         D         E          F
2985 -1.443039 -0.873042  0.286502  0.131774 -0.812787  -2.311916
2988  0.636137 -0.465677  0.677833 -0.541540 -0.302328  -1.075509
2991  1.428879 -0.855440  0.539704 -1.497891  0.004913  10.679053
2994  0.746677  0.246700  0.726296  1.238024  0.333257  -0.723054
2997  2.054665  0.848563 -0.652124 -1.153524 -0.171251 -17.765266
3003  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000   1.000000

New columns of data can just be asigned or added with the command `join`.

In [85]:
u['G'] = np.random.choice(['a', 'b', 'c'], len(u))
u.tail()

A         B         C         D         E          F  G
2985 -1.443039 -0.873042  0.286502  0.131774 -0.812787  -2.311916  b
2988  0.636137 -0.465677  0.677833 -0.541540 -0.302328  -1.075509  a
2991  1.428879 -0.855440  0.539704 -1.497891  0.004913  10.679053  c
2994  0.746677  0.246700  0.726296  1.238024  0.333257  -0.723054  c
2997  2.054665  0.848563 -0.652124 -1.153524 -0.171251 -17.765266  b

### Grouping Data

In [86]:
for h, group in u.groupby('G'):
    print('{}: {}'.format(h, np.mean(group['F'])))

a: 0.04803418405004595
b: 2.961722616193067
c: 0.29664938440176003


In [87]:
u.groupby('G').describe()

A                                                              \
   count      mean       std       min       25%       50%       75%   
G                                                                      
a  317.0  0.107822  0.990977 -2.799957 -0.432288  0.103228  0.777953   
b  340.0 -0.012748  1.006200 -3.388593 -0.741570 -0.076684  0.603936   
c  343.0 -0.024982  0.937233 -2.646094 -0.659933 -0.038974  0.612174   

                 B               ...             E                F            \
        max  count      mean     ...           75%       max  count      mean   
G                                ...                                            
a  3.761690  317.0 -0.063263     ...      0.690932  2.962746  317.0  0.048034   
b  2.768763  340.0 -0.001625     ...      0.696759  3.037953  340.0  2.961723   
c  2.540335  343.0  0.014253     ...      0.568424  2.734018  343.0  0.296649   

                                                                    
         std         min       25%       50%       75%         max  
G                                                                   
a   9.309405  -43.935627 -1.545327 -0.334599  1.341564  100.023294  
b  48.818677 -344.542678 -1.124981  0.693144  1.732119  723.150867  
c   8.047534  -71.486370 -1.403432  0.578978  1.427959   71.942956  

[3 rows x 48 columns]

### Loading and saving dataframes

To load and save Pandas dataframes we will use the `to_csv` and `read_csv` commands

In [88]:
u.to_csv('test.csv')
v = pd.read_csv('test.csv', index_col=0)
v.head()

A         B         C         D         E          F  G
0  -0.656352 -1.828935  1.356624 -2.031876  0.714026   3.104331  c
3  -0.731898 -0.040749  2.087230 -0.186705  0.925189 -34.629224  a
6   0.279463 -0.903286  0.542951  0.245455  0.736812   1.909168  c
9   0.517327  0.176194  0.106239 -2.695502 -0.318348 -21.598144  a
12 -0.657431 -0.841408 -1.749269  0.056158  0.171432  -5.400024  b

But, as an addition, Pandas has special commands to load and save Excel spreadsheets (yay!). However, to use it you'll need the `openpyxl` and `xlrd` packages.

In [89]:
u.to_excel('test.xlsx', sheet_name='My sheet')
pd.read_excel('test.xlsx', 'My sheet', index_col=0).head()

A         B         C         D         E          F  G
0  -0.656352 -1.828935  1.356624 -2.031876  0.714026   3.104331  c
3  -0.731898 -0.040749  2.087230 -0.186705  0.925189 -34.629224  a
6   0.279463 -0.903286  0.542951  0.245455  0.736812   1.909168  c
9   0.517327  0.176194  0.106239 -2.695502 -0.318348 -21.598144  a
12 -0.657431 -0.841408 -1.749269  0.056158  0.171432  -5.400024  b

**Exercise 5**: Download [this dataset](https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv) and load it, using the first column as the index. Take a look at it, and do the following things:
- Choose the columns 'Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1' and 'Type2' 
- Create a function that lowercases strings and apply it to 'Type1' and 'Type2' (*Extra: just capitalize the strings, i.e., leave the first letter uppercase and lowercase the rest*)
- Create a function that returns a Boolean value (don't be afraif by this, it is a function that returns either True or False) that tells if a Pokémon has high stamina (BaseStamina>170) or not. Store this information in a new column and show the list of Pokémon with high stamina
- Show the instructor the last 15 rows of your dataset

In [90]:
df = pd.read_csv('https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv', 
                 index_col=0)

df = df[['Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1', 'Type2']]

capitalize = lambda st: st.capitalize()

for col in ['Type1', 'Type2']:
    df[col] = df[col].apply(capitalize)
    
def highstamina(x):
    return True if x > 170 else False

df['HighStamina'] = df.BaseStamina.apply(highstamina)

print(df[df['HighStamina'] == True].Identifier)

df.tail(15)

PkMn
31      Nidoqueen
36       Clefable
39     Jigglypuff
40     Wigglytuff
59       Arcanine
62      Poliwrath
68        Machamp
          ...    
143       Snorlax
144      Articuno
145        Zapdos
146       Moltres
149     Dragonite
150        Mewtwo
151           Mew
Name: Identifier, Length: 26, dtype: object


Identifier  BaseStamina  BaseAttack  BaseDefense     Type1   Type2  \
PkMn                                                                       
137      Porygon          130         156          158    Normal    None   
138      Omanyte           70         132          160      Rock   Water   
139      Omastar          140         180          202      Rock   Water   
140       Kabuto           60         148          142      Rock   Water   
141     Kabutops          120         190          190      Rock   Water   
142   Aerodactyl          160         182          162      Rock  Flying   
143      Snorlax          320         180          180    Normal    None   
144     Articuno          180         198          242       Ice  Flying   
145       Zapdos          180         232          194  Electric  Flying   
146      Moltres          180         242          194      Fire  Flying   
147      Dratini           82         128          110    Dragon    None   
148    Dragonair          122         170          152    Dragon    None   
149    Dragonite          182         250          212    Dragon  Flying   
150       Mewtwo          212         284          202   Psychic    None   
151          Mew          200         220          220   Psychic    None   

      HighStamina  
PkMn               
137         False  
138         False  
139         False  
140         False  
141         False  
142         False  
143          True  
144          True  
145          True  
146          True  
147         False  
148         False  
149          True  
150          True  
151          True